/**
 * functions/src/telegram/inlineHandlers.ts
 *
 * Handles Telegram inline queries:
 *   @Nexus <query>
 *
 * Returns an array of InlineQueryResult objects.
 * Provides:
 *   - Instant Gemini text answer
 *   - Optional image generation (if user prefixes query with "img:")
 *
 * Connected modules:
 *   - generateText() from genai/geminiClient.ts
 *   - generateImage() from genai/geminiClient.ts (added later)
 *   - uploadBufferToStorage() from storage/imageUploader.ts
 */

import { InlineQuery } from "grammy/types";
import { InlineKeyboard } from "grammy";
import { generateText, generateImage } from "../genai/geminiClient";
import { uploadBufferToStorage } from "../storage/imageUploader";
import { FirebaseFirestore, Storage } from "firebase-admin";

interface InlineContext {
  db: FirebaseFirestore.Firestore;
  storage: Storage.Storage;
  generateText?: typeof generateText;
  generateImage?: typeof generateImage;
  uploadBufferToStorage?: typeof uploadBufferToStorage;
}

export async function handleInlineQuery(
  inlineQuery: InlineQuery,
  { db, storage }: InlineContext
) {
  const query = inlineQuery.query.trim();

  if (!query) {
    return [
      {
        type: "article",
        id: "empty",
        title: "Type something…",
        input_message_content: {
          message_text: "Start typing to ask Nexus something.",
        },
        description: "Nexus awaits your command.",
      },
    ];
  }

  /**
   * Special prefix:
   *   img: <prompt> → Gemini Image Generation
   */
  const isImageMode = query.startsWith("img:");
  if (isImageMode) {
    const prompt = query.replace("img:", "").trim();

    if (!prompt) {
      return [
        {
          type: "article",
          id: "img-empty",
          title: "Image prompt missing",
          input_message_content: {
            message_text: "Provide a prompt after `img:`",
          },
          description: "Example: img: futuristic neon cityscape",
        },
      ];
    }

    try {
      const apiKey = process.env.GEMINI_API_KEY || "";
      const buffer = await generateImage({ prompt, apiKey });

      const filename = `inline/generated-${Date.now()}.png`;
      const publicUrl = await uploadBufferToStorage({
        buffer,
        destinationPath: filename,
        contentType: "image/png",
      });

      await db.collection("inline_generations").add({
        prompt,
        url: publicUrl,
        createdAt: Date.now(),
      });

      return [
        {
          type: "photo",
          id: `img-${Date.now()}`,
          photo_url: publicUrl,
          thumb_url: publicUrl,
          caption: `Generated by Nexus\nPrompt: ${prompt}`,
        },
      ];
    } catch (err) {
      console.error("Inline image error:", err);
      return [
        {
          type: "article",
          id: "img-error",
          title: "Image generation failed",
          input_message_content: {
            message_text: "I failed to generate that image. Try again.",
          },
          description: "Gemini image generation error.",
        },
      ];
    }
  }

  /**
   * Default mode → Gemini text generation inline answer
   */

  try {
    const apiKey = process.env.GEMINI_API_KEY || "";
    const response = await generateText({ prompt: query, apiKey });

    const kb = new InlineKeyboard()
      .url("GitHub Repo", "https://github.com/Judson-web/NexAi-Neo")
      .row()
      .text("Ask Again", "ask_again");

    return [
      {
        type: "article",
        id: `text-${Date.now()}`,
        title: "Nexus Answer",
        input_message_content: {
          message_text: response,
        },
        description: response.slice(0, 80) + "...",
        reply_markup: kb,
      },
    ];
  } catch (err) {
    console.error("Inline text error:", err);

    return [
      {
        type: "article",
        id: "text-error",
        title: "Error",
        input_message_content: {
          message_text: "Nexus failed to think. Try again.",
        },
        description: "Gemini text generation error.",
      },
    ];
  }
}