import crypto from"node:crypto";
const SUPABASE_URL=process.env.SUPABASE_URL||"https://wocxvtptqapietlteshr.supabase.co";
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY;
const COOKIE="__Host-ks_dev_issuer";
const DAYS=100;
const hash=v=>crypto.createHash("sha256").update(String(v)).digest("hex");
const key=()=> "ks_live_"+crypto.randomBytes(32).toString("base64url");
const token=()=>crypto.randomBytes(32).toString("base64url");
function cookies(req){return String(req.headers.cookie||"").split(";").map(v=>v.trim()).reduce((a,v)=>{const i=v.indexOf("=");if(i>0)try{a[v.slice(0,i)]=decodeURIComponent(v.slice(i+1))}catch{}return a},{});}
function setCookie(res,value,maxAge){res.setHeader("Set-Cookie",COOKIE+"="+encodeURIComponent(value)+"; Max-Age="+maxAge+"; Path=/; HttpOnly; Secure; SameSite=Lax");}
function cors(res){res.setHeader("Access-Control-Allow-Origin",process.env.DEVELOPER_CORS_ORIGIN||"https://kingshot-autoredeemer.vercel.app");res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Headers","Content-Type");res.setHeader("Access-Control-Allow-Methods","POST, GET, DELETE, OPTIONS");res.setHeader("Cache-Control","no-store");}
function allowed(req){const origin=String(req.headers.origin||"");if(!origin)return true;return origin===String(process.env.DEVELOPER_APP_ORIGIN||"https://kingshot-autoredeemer.vercel.app").replace(/\/$/,"");}
async function db(path,options={}){if(!SUPABASE_KEY)throw Error("Developer key service is not configured.");const r=await fetch(SUPABASE_URL+"/rest/v1/"+path,{...options,headers:{"apikey":SUPABASE_KEY,"authorization":"Bearer "+SUPABASE_KEY,"content-type":"application/json",Prefer:"return=representation",...(options.headers||{})},signal:AbortSignal.timeout(8000)});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.message||"Developer key service unavailable.");return d}
export default async function handler(req,res){cors(res);if(req.method==="OPTIONS")return res.status(204).end();if(!allowed(req))return res.status(403).json({error:"Cross-origin developer key requests are not allowed."});if(!["POST","GET","DELETE"].includes(req.method))return res.status(405).json({error:"Method not allowed."});try{let issuer=cookies(req)[COOKIE];if(!issuer){issuer=token();setCookie(res,issuer,DAYS*86400)}const issuerHash=hash(issuer);if(req.method==="GET"){const rows=await db("kingshot_api_keys?select=id,name,key_prefix,active,requests_per_minute,daily_limit,total_requests,created_at,expires_at&issuer_hash=eq."+encodeURIComponent(issuerHash)+"&active=eq.true&limit=1");const k=rows?.[0];return res.status(200).json({key:k?{id:k.id,name:k.name,key_prefix:k.key_prefix,requests_per_minute:k.requests_per_minute,daily_limit:k.daily_limit,total_requests:k.total_requests,created_at:k.created_at,expires_at:k.expires_at}:null})}if(req.method==="DELETE"){await db("kingshot_api_keys?issuer_hash=eq."+encodeURIComponent(issuerHash)+"&active=eq.true",{method:"PATCH",body:JSON.stringify({active:false,updated_at:new Date().toISOString()})});return res.status(200).json({ok:true})}const existing=await db("kingshot_api_keys?select=id,active,expires_at&issuer_hash=eq."+encodeURIComponent(issuerHash)+"&active=eq.true&limit=1");if(existing?.length&&new Date(existing[0].expires_at||0)>new Date())return res.status(409).json({error:"This browser already has an active API key. Use the existing key or wait for it to expire."});const raw=key(),expires=new Date(Date.now()+DAYS*86400000).toISOString(),row=(await db("kingshot_api_keys",{method:"POST",body:JSON.stringify({name:"Browser Developer Key",key_prefix:raw.slice(0,18),key_hash:hash(raw),issuer_hash:issuerHash,active:true,requests_per_minute:2,daily_limit:100,total_requests:0,expires_at:expires})}))[0];return res.status(201).json({ok:true,key:raw,keyRecord:{id:row.id,name:row.name,key_prefix:row.key_prefix,requests_per_minute:row.requests_per_minute,daily_limit:row.daily_limit,created_at:row.created_at,expires_at:row.expires_at}})}catch(e){return res.status(502).json({error:e.message||"Could not issue developer API key."})}}