import React,{useEffect,useState}from"react";
import{LoaderCircle,LogOut,RefreshCw,ShieldCheck}from"lucide-react";
export default function AdminApp(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[players,setPlayers]=useState([]),[auth,setAuth]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const load=async()=>{setBusy(true);try{const r=await fetch("/api/kingshot-admin-data",{credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(r.status===401){setAuth(false);setPlayers([]);return}if(!r.ok)throw Error(d.error||"Could not load data.");setAuth(true);setPlayers(d.players||[])}catch(e){setError(e.message||"Could not load data.")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const login=async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-login",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Invalid credentials.");setPassword("");await load()}catch(e){setError(e.message||"Login failed.")}finally{setBusy(false)}};
 const logout=async()=>{await fetch("/api/kingshot-admin-login",{method:"DELETE",credentials:"same-origin"}).catch(()=>{});setAuth(false);setPlayers([])};
 return <div className="app ks-app admin-app"><header><div className="brand ks-brand"><span className="brand-mark">K</span><span>Kingshot Admin</span></div><div className="admin-badge"><ShieldCheck size={14}/> ADMIN</div></header><main>
 {!auth?<section className="admin-hero"><div className="eyebrow"><span/>PRIVATE ADMIN AREA</div><h1>Kingdom <em>Control.</em></h1><form className="admin-login" onSubmit={login}><label>EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="ks-submit" disabled={busy}>{busy?<><LoaderCircle size={15} className="spin"/> Signing in…</>:"Sign in"}</button></form>{error&&<div className="ks-error">{error}</div>}</section>
 :<section className="admin-panel"><div className="admin-head"><div><div className="eyebrow"><span/>KINGSHOT AUTO REDEEM</div><h1>Registered <em>players.</em></h1></div><div className="admin-actions"><button onClick={load} disabled={busy}><RefreshCw size={15}/> Refresh</button><button onClick={logout}><LogOut size={15}/> Sign out</button></div></div><div className="admin-stats"><div><small>REGISTERED</small><b>{players.length}</b></div><div><small>ACTIVE</small><b>{players.filter(p=>p.enabled).length}</b></div></div><div className="admin-table"><div className="admin-table-head"><span>PLAYER</span><span>PLAYER ID</span><span>KINGDOM</span><span>STATUS</span><span>LAST REDEEM</span></div>{busy?<div className="admin-empty">Loading…</div>:players.length?players.map(p=><div className="admin-row" key={p.id}><div className="admin-player"><div className="ks-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span>K</span>}</div><div><b>{p.player_name||"Kingshot Player"}</b><small>{p.created_at?new Date(p.created_at).toLocaleString():"—"}</small></div></div><code>{p.player_id}</code><span>{p.kingdom_id||"—"}</span><span className={p.enabled?"admin-status active":"admin-status"}>{p.enabled?"ACTIVE":"DISABLED"}</span><span>{p.last_redeem_at?new Date(p.last_redeem_at).toLocaleString():"Never"}</span></div>):<div className="admin-empty">No registrations.</div>}</div></section>}
 </main></div>
}