import React,{useEffect,useState}from"react";
import{ChevronDown,LoaderCircle,LogOut,RefreshCw,ShieldCheck,UserX,XCircle,Inbox,Gift,Plus,Megaphone}from"lucide-react";
const DISCORD_ID="871756466900598815";
const discordAvatarUrl=(user,size=64,format=user?.format||"png")=>"/api/discord-avatar?id="+encodeURIComponent(user.id)+"&hash="+encodeURIComponent(user.avatar)+"&format="+encodeURIComponent(format)+"&size="+encodeURIComponent(size);
function AdminDiscordChip(){const [user,setUser]=useState(null);useEffect(()=>{let live=true;fetch("/api/discord-user?id="+DISCORD_ID,{credentials:"same-origin"}).then(r=>r.ok?r.json():null).then(d=>{if(live&&d?.id)setUser(d)}).catch(()=>{});return()=>{live=false}},[]);const avatar=user?.avatar?discordAvatarUrl(user,64,user.animated?"gif":"png"):"https://cdn.discordapp.com/embed/avatars/0.png?size=64";return <a className="admin-credit" href={"https://discord.com/channels/@me/"+DISCORD_ID} target="_blank" rel="noreferrer" aria-label="Message Judson on Discord"><img src={avatar} alt="Judson" loading="eager" onError={e=>{e.currentTarget.src="https://cdn.discordapp.com/embed/avatars/0.png?size=64"}}/><span>Judson</span></a>}
class AdminErrorBoundary extends React.Component{
 constructor(props){super(props);this.state={failed:false}}
 static getDerivedStateFromError(){return {failed:true}}
 componentDidCatch(error){console.error("Admin dashboard render error:",error)}
 render(){
  if(this.state.failed)return <div className="app ks-app admin-app"><main><section className="admin-hero"><div className="eyebrow"><span/>ADMIN RECOVERY</div><h1>Dashboard <em>recovered.</em></h1><p className="hero-copy">The admin interface hit a rendering error. Your server-side data is safe.</p><button className="ks-submit" onClick={()=>location.reload()}>Reload admin</button></section></main></div>;
  return this.props.children;
 }
}
export default function AdminApp(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[players,setPlayers]=useState([]),[tickets,setTickets]=useState([]),[giftCodes,setGiftCodes]=useState([]),[auditLog,setAuditLog]=useState([]),[scraperComparison,setScraperComparison]=useState([]),[giftCode,setGiftCode]=useState(""),[sourceDate,setSourceDate]=useState(""),[auth,setAuth]=useState(false),[busy,setBusy]=useState(true),[codeBusy,setCodeBusy]=useState(false),[webhookBusy,setWebhookBusy]=useState(false),[error,setError]=useState(""),[codeError,setCodeError]=useState(""),[codeSuccess,setCodeSuccess]=useState(""),[webhookSuccess,setWebhookSuccess]=useState(""),[testTitle,setTestTitle]=useState("🧪 Webhook Test"),[testDescription,setTestDescription]=useState("Kingshot Auto Redeem webhook is connected successfully."),[testStatus,setTestStatus]=useState("Connected"),[testTriggeredBy,setTestTriggeredBy]=useState("Admin panel"),[testFooter,setTestFooter]=useState("Kingshot Redeemer"),[open,setOpen]=useState(null);
 const load=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-data",{credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(r.status===401){setAuth(false);setPlayers([]);setTickets([]);setGiftCodes([]);return}if(!r.ok)throw Error(d.error||"Could not load data.");setAuth(true);setPlayers((d.players||[]).filter(p=>p.enabled));setTickets(d.tickets||[]);setGiftCodes(d.giftCodes||[]);setAuditLog(d.auditLog||[]);setScraperComparison(d.scraperComparison||[])}catch(e){setError(e.message||"Could not load data.")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const login=async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-login",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Invalid credentials.");setPassword("");await load()}catch(e){setError(e.message||"Login failed.");setBusy(false)}};
 const logout=async()=>{await fetch("/api/kingshot-admin-login",{method:"DELETE",credentials:"same-origin"}).catch(()=>{});setAuth(false);setPlayers([]);setTickets([]);setGiftCodes([])};
 const ticketAction=async(id,action)=>{setBusy(true);try{const r=await fetch("/api/kingshot-admin-data",{method:"PATCH",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({ticketId:id,action})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not update ticket.");await load()}catch(e){setError(e.message||"Could not update ticket.");setBusy(false)}};
 const revokePlayer=async id=>{if(!confirm("Revoke auto-redeem registration for Player "+id+"?"))return;setBusy(true);try{const r=await fetch("/api/kingshot-admin-data",{method:"DELETE",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({playerId:id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not revoke registration.");await load()}catch(e){setError(e.message||"Could not revoke registration.");setBusy(false)}};
 const testWebhook=async()=>{setWebhookBusy(true);setWebhookSuccess("");setError("");try{const r=await fetch("/api/kingshot-admin-data",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"TEST_WEBHOOK",title:testTitle,description:testDescription,status:testStatus,triggeredBy:testTriggeredBy,footer:testFooter})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not send webhook test.");setWebhookSuccess("Test message sent to Discord.");}catch(e){setError(e.message||"Webhook test failed.")}finally{setWebhookBusy(false)}};
 const addGiftCode=async e=>{e.preventDefault();const code=giftCode.trim();if(!(code==="Kingshot888"||/^[A-Z0-9]{6,32}$/.test(code))){setCodeError("Use 6–32 uppercase letters/numbers. Kingshot888 is the documented mixed-case exception.");return}setCodeBusy(true);setCodeError("");setCodeSuccess("");try{const r=await fetch("/api/kingshot-admin-data",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({code,sourceDate:sourceDate||null})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not add gift code.");setGiftCodes(d.giftCodes||[]);setGiftCode("");setSourceDate("");setCodeSuccess((d.existing?"Reactivated":"Added")+" "+(d.code||code)+" to the active gift-code pool.");}catch(e){setCodeError(e.message||"Could not add gift code.")}finally{setCodeBusy(false)}};
 const playerForTicket=id=>players.find(p=>p.player_id===id);
 return <AdminErrorBoundary><div className="app ks-app admin-app"><header><div className="brand ks-brand"><span className="brand-mark">K</span><span>Kingshot Admin</span></div><div className="admin-header-right"><AdminDiscordChip/><div className="admin-badge"><ShieldCheck size={14}/> ADMIN</div></div></header><main>
 {!auth?<section className="admin-hero"><div className="eyebrow"><span/>PRIVATE ADMIN AREA</div><h1>Kingdom <em>Control.</em></h1><p className="hero-copy">Secure access to registrations, gift codes, and support requests.</p><form className="admin-login" onSubmit={login}><div className="admin-login-icon"><ShieldCheck size={20}/></div><label>EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" placeholder="Admin email" required/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" placeholder="Admin password" required/></label><button className="ks-submit" disabled={busy}>{busy?<><LoaderCircle size={15} className="spin"/> Signing in…</>:"Sign in securely"}</button></form>{error&&<div className="ks-error">{error}</div>}</section>
 :<section className="admin-panel"><div className="admin-head"><div><div className="eyebrow"><span/>KINGSHOT AUTO REDEEM</div><h1>Control <em>center.</em></h1><p>Registrations, player details, gift codes, and customer support requests.</p></div><div className="admin-actions"><button onClick={testWebhook} disabled={webhookBusy}>{webhookBusy?<><LoaderCircle size={14} className="spin"/> Testing…</>:<><Megaphone size={14}/> Test webhook</>}</button><a className="admin-action-link" href="/ad-admin"><Megaphone size={14}/> Ad Manager</a><button onClick={load} disabled={busy}><RefreshCw size={15}/> Refresh</button><button onClick={logout}><LogOut size={15}/> Sign out</button></div></div>
 <div className="admin-stats"><div><small>REGISTERED</small><b>{players.length}</b></div><div><small>ACTIVE</small><b>{players.filter(p=>p.enabled).length}</b></div><div><small>ACTIVE CODES</small><b>{giftCodes.length}</b></div><div><small>OPEN TICKETS</small><b>{tickets.filter(t=>t.status==="PENDING").length}</b></div></div>
 <div className="admin-section admin-code-section"><div className="admin-section-title"><Megaphone size={15}/><span>Discord webhook alerts</span><b className="admin-section-count">LIVE</b></div><p className="admin-section-note">The worker sends structured alerts for new gift codes, redemption results, scraper health, stale players, kingdom changes, worker errors, and active cycles. This uses a Discord webhook only — no Discord bot or slash commands are required.</p><div className="admin-webhook-status"><div><span className="admin-webhook-dot"></span><div><b>Webhook delivery</b><small>Configured server-side · protected from accidental @mentions</small></div></div><button className="admin-code-add" onClick={testWebhook} disabled={webhookBusy}>{webhookBusy?<><LoaderCircle size={15} className="spin"/> Sending…</>:<><Megaphone size={15}/> Send test alert</>}</button></div>{webhookSuccess&&<div className="admin-inline-success">{webhookSuccess}</div>}{error&&<div className="admin-inline-error">{error}</div>}</div>
 <div className="admin-section admin-code-section"><div className="admin-section-title"><Gift size={15}/><span>Gift-code control</span><b className="admin-section-count">{giftCodes.length}</b></div><p className="admin-section-note">Add a code directly to the same active pool used by the automatic worker. It will be checked against every enabled player on the next worker run.</p><form className="admin-code-form" onSubmit={addGiftCode}><label><span>GIFT CODE</span><div><Gift size={15}/><input value={giftCode} onChange={e=>setGiftCode(e.target.value.replace(/\s/g,""))} placeholder="e.g. NEWCODE2026" autoComplete="off" spellCheck="false" maxLength={64}/></div></label><label><span>SOURCE DATE <i>OPTIONAL</i></span><input type="date" value={sourceDate} onChange={e=>setSourceDate(e.target.value)}/></label><button className="admin-code-add" disabled={codeBusy}>{codeBusy?<><LoaderCircle size={15} className="spin"/> Adding…</>:<><Plus size={15}/> Add code</>}</button></form>{codeError&&<div className="admin-inline-error">{codeError}</div>}{codeSuccess&&<div className="admin-inline-success">{codeSuccess}</div>}<div className="admin-code-list">{giftCodes.length?giftCodes.map(c=><div className="admin-code-row" key={c.id||c.code}><code>{c.code}</code><span>{c.source_date?new Date(c.source_date+"T00:00:00").toLocaleDateString():"No source date"}</span><small>Seen {c.last_seen_at?new Date(c.last_seen_at).toLocaleString():"—"}</small></div>):<div className="admin-empty">No active gift codes.</div>}</div></div>
 <div className="admin-section"><div className="admin-section-title"><Inbox size={15}/><span>Support inbox</span></div>{tickets.length?tickets.map(t=>{const p=playerForTicket(t.player_id);return <div className={"admin-ticket "+(t.status==="PENDING"?"pending":"")} key={t.id}><div className="admin-ticket-main"><div className="admin-ticket-heading"><div className="admin-ticket-avatar">{p?.avatar_url?<img src={p.avatar_url} alt=""/>:<span>K</span>}</div><div className="admin-ticket-title"><div><b>{p?.player_name||"Kingshot Player"}</b><span className={"admin-ticket-status "+t.status.toLowerCase()}>{t.status}</span></div><small><code>{t.player_id}</code>{p?.kingdom_id&&<><span>•</span>Kingdom {p.kingdom_id}</>}<span>•</span>{new Date(t.created_at).toLocaleString()}</small></div></div><div className="admin-ticket-reason"><span>REMOVAL REASON</span><p>{t.reason}</p></div></div>}{t.status==="PENDING"&&<div className="admin-ticket-actions"><button className="admin-ticket-revoke" onClick={()=>ticketAction(t.id,"REVOKE")}><UserX size={14}/> Revoke</button><button className="admin-ticket-cancel" onClick={()=>ticketAction(t.id,"CANCEL")}><XCircle size={14}/> Cancel</button></div>}</div>}) :<div className="admin-empty">No support requests.</div>}</div>
 <div className="admin-section"><div className="admin-section-title"><RefreshCw size={15}/><span>Scraper source comparison</span><b className="admin-section-count">{scraperComparison.length}</b></div><p className="admin-section-note">Latest parsed result from each gift-code source. A 200 response is not treated as healthy unless usable codes were actually parsed.</p><div className="admin-code-list">{scraperComparison.length?scraperComparison.map(s=><div className="admin-code-row" key={s.source}><code>{s.source}</code><span>{s.code_count} codes · HTTP {s.http_status||"—"}</span><small>{s.parse_ok?"PARSED":"FAILED"}{s.error_category?" · "+s.error_category:""} · {s.checked_at?new Date(s.checked_at).toLocaleString():"—"}</small></div>):<div className="admin-empty">No scraper runs recorded yet.</div>}</div></div>
 <div className="admin-section"><div className="admin-section-title"><ShieldCheck size={15}/><span>Admin audit log</span><b className="admin-section-count">{auditLog.length}</b></div><p className="admin-section-note">Administrative mutations are recorded with actor, action, target and timestamp.</p><div className="admin-code-list">{auditLog.length?auditLog.map(a=><div className="admin-code-row" key={a.id}><code>{a.action}</code><span>{a.target_type||"system"}{a.target_id?" · "+a.target_id:""}</span><small>{a.actor_email} · {a.created_at?new Date(a.created_at).toLocaleString():"—"}</small></div>):<div className="admin-empty">No audit events yet.</div>}</div></div>
 <div className="admin-section"><div className="admin-section-title"><ShieldCheck size={15}/><span>Registered players</span><b className="admin-section-count">{players.length}</b></div><div className="admin-table admin-player-list">{busy?<div className="admin-empty"><LoaderCircle size={17} className="spin"/> Loading…</div>:players.length?players.map(p=><div key={p.id} className={"admin-user-card "+(open===p.id?"open":"")}><button className="admin-user-summary" onClick={()=>setOpen(open===p.id?null:p.id)}><div className="admin-player"><div className="ks-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span>K</span>}</div><div><b>{p.player_name||"Kingshot Player"}</b><small>Player ID {p.player_id}</small></div></div><span className={p.stale?"admin-status stale":(p.enabled?"admin-status active":"admin-status")}>{p.stale?"STALE":(p.enabled?"ACTIVE":"REVOKED")}</span><ChevronDown size={16}/></button>{open===p.id&&<div className="admin-user-details"><div><small>PLAYER ID</small><b>{p.player_id}</b></div><div><small>KINGDOM</small><b>{p.kingdom_id||"—"}</b></div><div><small>REGISTERED</small><b>{p.created_at?new Date(p.created_at).toLocaleString():"—"}</b></div><div><small>LAST REDEEM</small><b>{p.last_redeem_at?new Date(p.last_redeem_at).toLocaleString():"Never"}</b></div><div><small>KINGDOM CHECK</small><b>{p.last_kingdom_check_at?new Date(p.last_kingdom_check_at).toLocaleString():"Never"}</b></div>{p.stale&&<div><small>STALE REASON</small><b>{p.stale_reason||"Player could not be found."}</b></div>}<button className="admin-revoke" disabled={!p.enabled||busy} onClick={()=>revokePlayer(p.player_id)}><UserX size={14}/> Revoke registration</button></div>}</div>):<div className="admin-empty">No registrations.</div>}</div></div>
 {error&&<div className="ks-error">{error}</div>}{webhookSuccess&&<div className="admin-inline-success">{webhookSuccess}</div>}</section>}
 </main></div></AdminErrorBoundary>
}