import React,{useEffect,useState}from"react";
import{ChevronDown,LoaderCircle,LogOut,RefreshCw,ShieldCheck,UserX,XCircle,Inbox,Github,ExternalLink}from"lucide-react";
export default function AdminApp(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[players,setPlayers]=useState([]),[tickets,setTickets]=useState([]),[auth,setAuth]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(null);
 const load=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-data",{credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(r.status===401){setAuth(false);setPlayers([]);setTickets([]);return}if(!r.ok)throw Error(d.error||"Could not load data.");setAuth(true);setPlayers(d.players||[]);setTickets(d.tickets||[])}catch(e){setError(e.message||"Could not load data.")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const login=async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-login",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Invalid credentials.");setPassword("");await load()}catch(e){setError(e.message||"Login failed.");setBusy(false)}};
 const logout=async()=>{await fetch("/api/kingshot-admin-login",{method:"DELETE",credentials:"same-origin"}).catch(()=>{});setAuth(false);setPlayers([]);setTickets([])};
 const ticketAction=async(id,action)=>{setBusy(true);try{const r=await fetch("/api/kingshot-admin-data",{method:"PATCH",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({ticketId:id,action})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not update ticket.");await load()}catch(e){setError(e.message||"Could not update ticket.");setBusy(false)}};
 const revokePlayer=async(id)=>{if(!confirm("Revoke auto-redeem registration for Player "+id+"?"))return;setBusy(true);try{const r=await fetch("/api/kingshot-admin-data",{method:"DELETE",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({playerId:id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not revoke registration.");await load()}catch(e){setError(e.message||"Could not revoke registration.");setBusy(false)}};
 return <div className="app ks-app admin-app"><header><div className="brand ks-brand"><span className="brand-mark">K</span><span>Kingshot Admin</span></div><div className="admin-header-right"><a className="admin-credit" href="https://discord.com/channels/@me/871756466900598815" target="_blank" rel="noreferrer" aria-label="Message Judson on Discord"><img src="https://github.com/Judson-web.png?size=96" alt="Judson"/><span>Judson</span></a><div className="admin-badge"><ShieldCheck size={14}/> ADMIN</div></div></header><main>
 {!auth?<section className="admin-hero"><div className="eyebrow"><span/>PRIVATE ADMIN AREA</div><h1>Kingdom <em>Control.</em></h1><p className="hero-copy">Secure access to registrations and support requests.</p><form className="admin-login" onSubmit={login}><div className="admin-login-icon"><ShieldCheck size={20}/></div><label>EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" placeholder="Admin email" required/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" placeholder="Admin password" required/></label><button className="ks-submit" disabled={busy}>{busy?<><LoaderCircle size={15} className="spin"/> Signing in…</>:"Sign in securely"}</button></form>{error&&<div className="ks-error">{error}</div>}</section>
 :<section className="admin-panel"><div className="admin-head"><div><div className="eyebrow"><span/>KINGSHOT AUTO REDEEM</div><h1>Control <em>center.</em></h1><p>Registrations, player details, and customer support requests.</p></div><div className="admin-actions"><button onClick={load} disabled={busy}><RefreshCw size={15}/> Refresh</button><button onClick={logout}><LogOut size={15}/> Sign out</button></div></div>
 <div className="admin-stats"><div><small>REGISTERED</small><b>{players.length}</b></div><div><small>ACTIVE</small><b>{players.filter(p=>p.enabled).length}</b></div><div><small>OPEN TICKETS</small><b>{tickets.filter(t=>t.status==="PENDING").length}</b></div></div>
 <div className="admin-section"><div className="admin-section-title"><Inbox size={15}/><span>Support inbox</span></div>{tickets.length?tickets.map(t=><div className={"admin-ticket "+(t.status==="PENDING"?"pending":"")} key={t.id}><div><div className="admin-ticket-top"><code>{t.player_id}</code><span>{t.status}</span></div><p>{t.reason}</p><small>{new Date(t.created_at).toLocaleString()}</small></div>{t.status==="PENDING"&&<div className="admin-ticket-actions"><button onClick={()=>ticketAction(t.id,"REVOKE")}><UserX size={14}/> Revoke registration</button><button onClick={()=>ticketAction(t.id,"CANCEL")}><XCircle size={14}/> Cancel</button></div>}</div>):<div className="admin-empty">No support requests.</div>}</div>
 <div className="admin-section"><div className="admin-section-title"><ShieldCheck size={15}/><span>Registered players</span><b className="admin-section-count">{players.length}</b></div><div className="admin-table admin-player-list">{busy?<div className="admin-empty"><LoaderCircle size={17} className="spin"/> Loading…</div>:players.length?players.map(p=><div key={p.id} className={"admin-user-card "+(open===p.id?"open":"")}><button className="admin-user-summary" onClick={()=>setOpen(open===p.id?null:p.id)}><div className="admin-player"><div className="ks-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span>K</span>}</div><div><b>{p.player_name||"Kingshot Player"}</b><small>Player ID {p.player_id}</small></div></div><span className={p.enabled?"admin-status active":"admin-status"}>{p.enabled?"ACTIVE":"REVOKED"}</span><ChevronDown size={16}/></button>{open===p.id&&<div className="admin-user-details"><div><small>PLAYER ID</small><b>{p.player_id}</b></div><div><small>KINGDOM</small><b>{p.kingdom_id||"—"}</b></div><div><small>REGISTERED</small><b>{p.created_at?new Date(p.created_at).toLocaleString():"—"}</b></div><div><small>LAST REDEEM</small><b>{p.last_redeem_at?new Date(p.last_redeem_at).toLocaleString():"Never"}</b></div><button className="admin-revoke" disabled={!p.enabled||busy} onClick={()=>revokePlayer(p.player_id)}><UserX size={14}/> Revoke registration</button></div>}</div>):<div className="admin-empty">No registrations.</div>}</div></div>
 {error&&<div className="ks-error">{error}</div>}</section>}
 </main></div>
}