import React,{useEffect,useState}from"react";
import{Megaphone,Plus,Pencil,Trash2,RefreshCw,LoaderCircle,ExternalLink,CheckCircle,AlertTriangle,Info,OctagonAlert}from"lucide-react";
const empty={id:null,title:"",message:"",type:"info",link_url:"",link_label:"",published_at:"",expires_at:"",active:true};
const localDateTime=v=>{if(!v)return"";const d=new Date(v);if(Number.isNaN(d.getTime()))return"";const p=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())+"T"+p(d.getHours())+":"+p(d.getMinutes())};
const icon=t=>t==="success"?CheckCircle:t==="warning"?AlertTriangle:t==="important"?OctagonAlert:Info;
export function AnnouncementsAdmin(){
 const[auth,setAuth]=useState(false),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const load=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-data",{credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.status===401){setAuth(false);setItems([]);return}if(!r.ok)throw Error(d.error||"Could not load announcements.");setAuth(true);setItems(d.announcements||[])}catch(e){setError(e.message||"Could not load announcements.")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const login=async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-login",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Invalid credentials.");setPassword("");await load()}catch(e){setError(e.message||"Login failed.");setBusy(false)}};
 const logout=async()=>{await fetch("/api/kingshot-admin-login",{method:"DELETE",credentials:"same-origin"}).catch(()=>{});setAuth(false);setItems([])};
 const reset=()=>{setForm({...empty});setEditing(false);setError("")};
 const edit=a=>{setForm({...empty,...a,published_at:localDateTime(a.published_at),expires_at:localDateTime(a.expires_at)});setEditing(true);window.scrollTo({top:0,behavior:"smooth"})};
 const save=async e=>{e.preventDefault();if(!form.title.trim()||!form.message.trim()){setError("Title and message are required.");return}if(form.expires_at&&form.published_at&&new Date(form.expires_at)<=new Date(form.published_at)){setError("Expiry must be later than publish time.");return}setSaving(true);setError("");try{const r=await fetch("/api/kingshot-admin-data",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({announcementAction:"upsert",...form,id:form.id||null,published_at:form.published_at?new Date(form.published_at).toISOString():null,expires_at:form.expires_at?new Date(form.expires_at).toISOString():null})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not save announcement.");setItems(d.announcements||[]);reset()}catch(e){setError(e.message||"Could not save announcement.")}finally{setSaving(false)}};
 const remove=async id=>{if(!confirm("Delete this announcement permanently?"))return;setSaving(true);try{const r=await fetch("/api/kingshot-admin-data",{method:"DELETE",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({announcementAction:"delete",id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not delete announcement.");setItems(d.announcements||[]);if(form.id===id)reset()}catch(e){setError(e.message||"Could not delete announcement.")}finally{setSaving(false)}};
 if(busy)return <div className="app ad-admin-app"><main className="ad-admin-loading"><LoaderCircle className="spin" size={24}/><span>Checking admin session…</span></main></div>;
 if(!auth)return <div className="app ad-admin-app"><header><a className="brand ks-brand" href="/"><span className="brand-mark">K</span><span>Kingshot Admin</span></a><div className="admin-badge">ADMIN ONLY</div></header><main className="ad-login-wrap"><section className="ad-login-card"><div className="eyebrow"><span/>SECURE ANNOUNCEMENTS</div><h1>Announcement<br/><em>control room.</em></h1><p>Sign in with the existing Kingshot admin account to publish site announcements.</p><form onSubmit={login}><label>ADMIN EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>ADMIN PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="ks-submit" disabled={busy}>Sign in</button></form>{error&&<div className="ks-error">{error}</div>}</section></main></div>;
 return <div className="app ad-admin-app"><header><a className="brand ks-brand" href="/"><span className="brand-mark">K</span><span>Kingshot Admin</span></a><nav><a href="/ks-admin">Admin</a><a href="/announcements-admin">Announcements</a><a href="/ad-admin">Ads</a></nav><div className="header-right"><div className="admin-badge">ADMIN</div><button className="menu-btn" onClick={logout} aria-label="Sign out">×</button></div></header>
 <main className="ad-admin-main"><section className="ad-admin-head"><div><div className="eyebrow"><span/>SITE ANNOUNCEMENTS</div><h1>Tell visitors<br/><em>what matters.</em></h1><p>Publish compact updates, new-code notices and service information without touching maintenance mode or the auto-redeem worker.</p></div><div className="ad-head-actions"><button className="ad-ghost" onClick={load}><RefreshCw size={14}/> Refresh</button><button className="ad-primary" onClick={reset}><Plus size={15}/> New announcement</button></div></section>
 {error&&<div className="admin-inline-error">{error}</div>}
 <div className="ad-admin-grid"><section className="ad-editor"><div className="ad-editor-head"><div><span className="result-label">{editing?"EDIT ANNOUNCEMENT":"CREATE ANNOUNCEMENT"}</span><h2>{editing?"Update announcement":"New announcement"}</h2></div>{editing&&<button className="ad-ghost" onClick={reset}>Cancel</button>}</div>
 <form onSubmit={save} className="ad-form"><div className="ad-form-section"><div className="ad-form-section-head"><span>01</span><div><b>Message</b><small>Keep it short and useful.</small></div></div><label>TITLE<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} maxLength={120} placeholder="New gift code available" required/></label><label>MESSAGE<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} maxLength={1000} rows={5} placeholder="Tell visitors what changed…" required/></label><div className="ad-form-two"><label>TYPE<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="important">Important</option></select></label><label>BUTTON LABEL<input value={form.link_label} onChange={e=>setForm({...form,link_label:e.target.value})} maxLength={50} placeholder="View details"/></label></div><label>LINK URL<input value={form.link_url} onChange={e=>setForm({...form,link_url:e.target.value})} placeholder="https://example.com"/></label></div>
 <div className="ad-form-section"><div className="ad-form-section-head"><span>02</span><div><b>Delivery</b><small>Publish now, schedule ahead, or let it expire automatically.</small></div></div><div className="ad-form-two"><label>PUBLISH AT<input type="datetime-local" value={form.published_at} onChange={e=>setForm({...form,published_at:e.target.value})}/></label><label>EXPIRES AT<input type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})}/></label></div><label className="ad-toggle"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span><b>Announcement enabled</b><small>Only enabled announcements inside their schedule appear publicly.</small></span></label></div>
 <div className="ad-form-actions"><button type="button" className="ad-ghost" onClick={reset}>Reset</button><button className="ad-primary ad-save" disabled={saving}>{saving?<><LoaderCircle size={15} className="spin"/> Saving…</>:<><Megaphone size={15}/> {editing?"Update":"Publish"} announcement</>}</button></div></form></section>
 <section className="ad-preview-panel"><div className="ad-editor-head"><div><span className="result-label">LIVE PREVIEW</span><h2>What visitors see</h2></div></div><AnnouncementCard item={form} preview/></section></div>
 <section className="ad-list-section"><div className="ad-editor-head"><div><span className="result-label">PUBLISHED</span><h2>Announcements</h2></div><div className="ad-rotation-note"><Megaphone size={12}/><span>Only active announcements inside their schedule are shown publicly.</span></div></div><div className="ad-list">{items.length?items.map(a=><article className="ad-row" key={a.id}><div className="ad-row-thumb"><Icon type={a.type}/></div><div className="ad-row-main"><div><b>{a.title}</b><span>{a.type} · {a.active?"enabled":"disabled"} · {new Date(a.published_at).toLocaleString()}</span><div className="ad-status live">{a.expires_at?"Expires "+new Date(a.expires_at).toLocaleString():"No expiry"}</div></div><div className="ad-row-metrics"><span>{a.link_url?"Linked":"No link"}</span><span>{a.message.length}/1000 chars</span></div></div><div className="ad-row-actions"><button className="ad-action-edit" onClick={()=>edit(a)}><Pencil size={13}/> Edit</button><button className="ad-action-delete" onClick={()=>remove(a.id)}><Trash2 size={13}/> Delete</button></div></article>):<div className="ad-empty"><Megaphone size={22}/><b>No announcements yet</b><span>Create one above and it will appear on the public site.</span></div>}</div></section></main></div>
}
function Icon({type}){const C=icon(type);return <C size={20}/>}
export function AnnouncementCard({item,preview=false}){if(!item)return null;const C=icon(item.type||"info");return <aside className={"site-announcement site-announcement-"+(item.type||"info")}><div className="site-announcement-icon"><C size={17}/></div><div className="site-announcement-content"><b>{item.title||"Announcement title"}</b><p>{item.message||"Your announcement message will appear here."}</p>{item.link_url&&<a href={item.link_url} target="_blank" rel="noopener noreferrer">{item.link_label||"Learn more"} <ExternalLink size={11}/></a>}</div>{!preview&&<span className="site-announcement-live">LIVE</span>}</aside>}
