import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{Check,CheckCircle,Copy,ExternalLink,KeyRound,LoaderCircle,LogOut,ShieldCheck,Terminal,Trash2,Eye,EyeOff,MailCheck,LockKeyhole,Activity,AlertTriangle,RefreshCw}from"lucide-react";
import"./developer.css";

const API_BASE="https://kingshot-autoredeemer.vercel.app/api/v1";
const copyText=async text=>{try{await navigator.clipboard.writeText(text);return true}catch{return false}};

function Header(){return <header className="dev-top"><div className="dev-shell dev-top-inner"><a className="dev-brand" href="/"><span className="dev-mark">K</span><span>Kingshot Developer</span></a><nav className="dev-nav"><a href="#overview">Overview</a><a href="#docs">Docs</a><a href="#examples">Examples</a><a href="#limits">Limits</a></nav><div className="dev-account"><a className="dev-btn" href="/info">Service info</a></div></div></header>}

function Docs(){return <><section className="dev-section" id="docs"><div className="dev-section-head"><div><h2>Developer API</h2><p>Server-side Kingshot gift-code redemption for applications, bots, scheduled workers, and automated backfill.</p></div><span className="dev-pill good"><CheckCircle size={11}/> v1 stable</span></div><div className="dev-doc-intro"><div><small>BASE URL</small><code>{API_BASE}</code></div><div><small>AUTHENTICATION</small><strong>Bearer API key</strong></div><div><small>TRANSPORT</small><strong>HTTPS / JSON</strong></div></div><div className="dev-grid"><article className="dev-endpoint"><div className="dev-endpoint-top"><span className="method">POST</span><span className="path">/api/v1/redeem</span></div><p>Redeem one eligible gift code for an authorized Kingshot Player ID.</p><div className="dev-param"><b>playerId</b><span>string · 4–32 digits</span></div><div className="dev-param"><b>kingdomId</b><span>string · 1–8 digits</span></div><div className="dev-param"><b>code</b><span>string · 3–64 letters, numbers, _ or -</span></div></article><article className="dev-endpoint"><div className="dev-endpoint-top"><span className="method">GET</span><span className="path">/api/v1/health</span></div><p>Public availability and service health check. No API key required.</p><div className="dev-param"><b>Authentication</b><span>None</span></div><div className="dev-param"><b>Response</b><span>JSON</span></div></article></div></section><section className="dev-section" id="examples"><div className="dev-section-head"><div><h2>Quick start</h2><p>Keep your API key on your backend. The upstream signing credentials never leave our service.</p></div></div><div className="dev-steps"><div><b>01</b><span><strong>Get an API key</strong>Request a key through the current access process and keep it on your backend.</span></div><div><b>02</b><span><strong>Store it securely</strong>Use a server-side secret manager or environment variable.</span></div><div><b>03</b><span><strong>Send a request</strong>Use the Bearer key and the required redemption fields.</span></div><div><b>04</b><span><strong>Track the result</strong>Persist the request ID and redemption status in your system.</span></div></div><h3 className="dev-subhead">Request</h3><pre className="dev-code">{`curl -X POST ${API_BASE}/redeem \\\n  -H "Authorization: Bearer ks_live_YOUR_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{"playerId":"123456789","kingdomId":"1125","code":"EXAMPLECODE"}'`}</pre><h3 className="dev-subhead">Success response</h3><pre className="dev-code">{`{
  "ok": true,
  "status": "SUCCESS",
  "statusLabel": "Redeemed",
  "message": "Gift code redeemed successfully.",
  "errCode": null,
  "requestId": "…"
}`}</pre></section><section className="dev-section"><div className="dev-section-head"><div><h2>Automation & backfill</h2><p>Automation is an intended use case when it stays inside the service controls.</p></div><span className="dev-pill"><Activity size={11}/> Server-side</span></div><div className="dev-policy-grid"><div><strong>Auto-redeem</strong><p>Scheduled workers, bots, and backend services may periodically discover eligible public codes and redeem them for authorized Player IDs.</p></div><div><strong>Backfill</strong><p>Catch up on still-eligible codes missed while offline, before registration, or during a temporary interruption.</p></div><div><strong>Retry safely</strong><p>Use reasonable backoff and stop when the API or upstream service indicates that further attempts should not be made.</p></div><div><strong>Prevent duplicates</strong><p>Persist redemption outcomes and avoid repeatedly submitting codes that have already been handled.</p></div></div><div className="dev-notice"><ShieldCheck size={13}/> Automation does not bypass quotas, cooldowns, rate limits, eligibility checks, or duplicate-prevention controls.</div></section><section className="dev-section"><div className="dev-section-head"><div><h2>Limits & errors</h2><p>Design your integration around stable HTTP behavior and request IDs.</p></div></div><div className="dev-limit-grid"><div><strong>2</strong><span>requests / minute / key</span></div><div><strong>100</strong><span>requests / day / key</span></div><div><strong>3</strong><span>active keys / account</span></div></div><div className="dev-error-list"><div><code>400</code><span>Invalid request fields or malformed input.</span></div><div><code>401</code><span>Missing, invalid, or inactive API key.</span></div><div><code>429</code><span>Per-minute or daily quota exceeded. Respect <code>Retry-After</code>.</span></div><div><code>5xx</code><span>Temporary service or upstream failure. Retry conservatively when appropriate.</span></div></div></section><section className="dev-section"><div className="dev-section-head"><div><h2>Security & acceptable use</h2><p>Build integrations that protect both your credentials and the service.</p></div></div><div className="dev-security-grid"><div><strong>Keep keys private</strong><p>Never expose <code>ks_live_…</code> keys in browser code, mobile apps, public repositories, logs, or frontend environment variables.</p></div><div><strong>Authorized players only</strong><p>Only submit Player IDs you are authorized to operate.</p></div><div><strong>No limit bypassing</strong><p>Do not rotate keys, accounts, IPs, or identities to evade quotas or other safeguards.</p></div><div><strong>No abuse</strong><p>No flooding, probing, credential theft, phishing, fraud, malware, DoS, private-data harvesting, or request manipulation.</p></div></div><div className="dev-notice"><Terminal size={13}/> The Developer API is an independent community interface and is not an official Century Games API.</div></section></>}


export default function DevelopersApp(){return <div className="dev-app"><Header/><main className="dev-main"><div className="dev-shell"><section className="dev-hero" id="overview"><div><div className="dev-eyebrow"><i/> DEVELOPER PLATFORM</div><h1>Build on<br/><em>Kingshot.</em></h1><p className="dev-copy">A professional server-side API for Kingshot gift-code redemption. Integrate once and keep the upstream game credentials safely behind your own backend.</p></div><div className="dev-hero-card"><small>API BASE URL</small><div className="dev-base-url">{API_BASE}</div><div className="dev-notice"><ShieldCheck size={13}/> Independent community API · not an official Century Games API.</div></div></section><section className="dev-access-card"><div><span className="dev-access-kicker">API ACCESS</span><h2>Server-side access, built for integrations.</h2><p>API keys are currently provisioned manually. The self-service account flow has been removed from the public developer experience while it is being rebuilt, so authentication issues cannot block the documentation or API itself.</p></div><div className="dev-access-points"><span><ShieldCheck size={13}/> Bearer authentication</span><span><LockKeyhole size={13}/> Keys stored as hashes</span><span><Activity size={13}/> Rate limited per key</span></div></section><Docs/></div></main><footer className="dev-footer"><div className="dev-shell">Kingshot Auto Redeem · Developer API · <a href="/terms?service=developer-api">Terms</a> · <a href="/privacy?service=developer-api">Privacy</a> · <a href="/info">Service information</a></div></footer></div>}

createRoot(document.getElementById("root")).render(<DevelopersApp/>);
