import React,{useEffect,useState} from "react";
import {ArrowLeft, CheckCircle, Clock3, Database, Gift, History, LockKeyhole, RefreshCw, Sparkles, Zap, Menu, X} from "lucide-react";
const KINGSHOT_ICON="https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/ee/d2/22/eed22297-9313-d8b0-52c8-95f42a2795b2/AppIcon-0-0-1x_U007emarketing-0-8-0-85-220.png/0x0ss-85.png";
function KsLogo(){return <a className="brand ks-brand" href="/"><span className="brand-mark ks-brand-mark"><img src={KINGSHOT_ICON} alt="Kingshot"/></span><span>Kingshot Redeemer</span></a>}
function DiscordChip(){const [user,setUser]=useState(null);useEffect(()=>{let live=true;fetch("/api/discord-user?id=871756466900598815",{credentials:"same-origin"}).then(r=>r.ok?r.json():null).then(d=>{if(live&&d?.id)setUser(d)}).catch(()=>{});return()=>{live=false}},[]);const avatar=user?.avatar?`/api/discord-avatar?id=${encodeURIComponent(user.id)}&hash=${encodeURIComponent(user.avatar)}&format=${encodeURIComponent(user.animated?"gif":"png")}&size=64`:"https://cdn.discordapp.com/embed/avatars/0.png?size=64";return <a className="admin-credit site-discord-credit" href="https://discord.com/channels/@me/871756466900598815" target="_blank" rel="noreferrer" aria-label="Message Judson on Discord"><img src={avatar} alt="Judson"/><span>Judson</span></a>}

const sections=[
 {icon:Zap,title:"Automatic redemption",text:"Register your Kingshot Player ID once. The service checks the active gift-code pool automatically and processes eligible codes without requiring you to return and redeem them manually."},
 {icon:History,title:"Backfill for older codes",text:"Backfill is built into the normal redemption flow. When a code is still active and your player has not handled it before, the system can pick it up even if you registered after the code was discovered."},
 {icon:Database,title:"Persistent redemption history",text:"Each player/code combination is tracked so the same redemption is not repeatedly attempted. The history also records the result returned by the game service."},
 {icon:RefreshCw,title:"Live code discovery",text:"Codes are collected from multiple public sources and normalized into one active pool. Duplicate entries are collapsed, and codes known to be expired are filtered out."},
 {icon:ShieldCheck,title:"Server-side redemption",text:"The game redemption request is submitted from the server. Signing material and privileged database credentials are kept away from the browser."},
 {icon:LockKeyhole,title:"Protected registration",text:"Public endpoints use validation, rate limits, and server-side checks. Registration does not require your Kingshot password or account credentials."},
];

function InfoApp(){
 const [menu,setMenu]=useState(false);
 const goBack=()=>{if(history.length>1)history.back();else location.href="/auto"};
 return <div className="app ks-app info-app">
  <a className="skip-link" href="#main-content">Skip to main content</a>
  <header><KsLogo/><nav><a href="/auto">Auto Redeem</a><a href="/manual">Manual Redeem</a><a className="active" href="/info">How it works</a></nav><div className="header-right"><DiscordChip/><button className="menu-btn" onClick={()=>setMenu(v=>!v)} aria-label="Menu">{menu?<X size={18}/>:<Menu size={18}/>}</button></div></header>
  {menu&&<div className="info-mobile-menu"><a href="/auto" onClick={()=>setMenu(false)}>Auto Redeem</a><a href="/manual" onClick={()=>setMenu(false)}>Manual Redeem</a><a href="/info" onClick={()=>setMenu(false)}>How it works</a></div>}
  <main id="main-content">
   <section className="info-hero"><button className="info-back" onClick={goBack}><ArrowLeft size={14}/> Back</button><div className="eyebrow"><span/>ABOUT THE SERVICE</div><h1>How Kingshot<br/><em>Auto Redeem works.</em></h1><p className="hero-copy">A plain-English guide to the features behind the service, from code discovery and backfill to redemption history and protection.</p></section>
   <section className="info-flow"><div className="section-title"><span>01</span><h2>The basic flow.</h2></div><div className="info-steps"><article><b>01</b><div><strong>Register your player</strong><p>Your Player ID is looked up so the current kingdom can be associated with the registration.</p></div></article><article><b>02</b><div><strong>Codes enter the active pool</strong><p>Public code sources are checked and normalized. Codes that are known to be expired are excluded.</p></div></article><article><b>03</b><div><strong>Workers process eligible players</strong><p>Registered players are distributed across a durable worker pool. Each worker processes its assigned shard concurrently.</p></div></article><article><b>04</b><div><strong>Results are remembered</strong><p>Each player/code attempt is claimed and recorded, preventing duplicate work while preserving the redemption result.</p></div></article></div></section>
   <section className="info-features"><div className="section-title"><span>02</span><h2>What the service does.</h2></div><div className="info-grid">{sections.map(({icon:Icon,title,text})=><article key={title}><div className="info-icon"><Icon size={18}/></div><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
   <section className="info-backfill"><div className="info-callout-icon"><Gift size={20}/></div><div><span className="result-label">BACKFILL, EXPLAINED</span><h2>Joining later does not mean missing every valid code.</h2><p>The system keeps redemption history per player. During normal processing it looks for the newest active code that the player has not already handled. If older active codes remain eligible, later runs can work through them as well.</p><small>Backfill is state-driven, not a separate one-time job. It uses the same redemption and duplicate-prevention rules as normal processing.</small></div></section>
   <section className="info-notes"><div><Clock3 size={16}/><div><b>Runs continuously</b><span>The production scheduler invokes the coordinator every minute.</span></div></div><div><Sparkles size={16}/><div><b>One service, multiple tools</b><span>Use Auto Redeem for hands-off processing or Manual Redeem when you want to submit a specific code yourself.</span></div></div><div><CheckCircle size={16}/><div><b>Clear outcomes</b><span>Game responses are translated into readable statuses such as successful, already handled, expired, invalid, or rate limited.</span></div></div></section>
  </main>
  <footer><KsLogo/><span>Independent Kingshot community service. Not affiliated with Century Games.</span><span><a href="/info">How it works</a> · <a href="/terms?service=kingshot-auto">Terms</a> · <a href="/privacy?service=kingshot-auto">Privacy</a></span></footer>
 </div>
}
export default InfoApp;
