import React,{useCallback,useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{ArrowUpRight,Bookmark,Clock3,Compass,Globe2,Image as ImageIcon,Menu,Newspaper,Play,Search,Settings,SlidersHorizontal,Sparkles,Video,X,Zap}from"lucide-react";
import"./styles.css";
const RECENT="nexus-recent",SAVED="nexus-saved",SECTIONS=[["all","Discover",Search],["images","Visuals",ImageIcon],["news","Pulse",Newspaper],["videos","Watch",Video]];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const queryOf=()=>new URLSearchParams(location.search).get("q")?.trim()||"",typeOf=()=>{const t=new URLSearchParams(location.search).get("type")||"all";return SECTIONS.some(x=>x[0]===t)?t:"all"},pageOf=()=>{const p=location.pathname.replace(/\/+$/,"")||"/";return["settings","about","advanced"].includes(p.slice(1))?p.slice(1):"search"};
const domain=u=>{try{return new URL(u).hostname.replace(/^www\./,"")}catch{return""}},fav=u=>{const d=domain(u);return d?"https://www.google.com/s2/favicons?domain="+encodeURIComponent(d)+"&sz=64":""};

function SearchBox({value,onChange,onSubmit,hero}){return <form className={hero?"nexus-search hero-search":"nexus-search"} onSubmit={e=>{e.preventDefault();onSubmit()}}><span className="search-symbol"><Search size={hero?21:18}/></span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={hero?"Explore anything…":"Search Nexus"} aria-label="Search Nexus" autoComplete="off"/>{value&&<button type="button" className="clear" onClick={()=>onChange("")}><X size={16}/></button>}<kbd>↵</kbd></form>}
function Logo({small}){return <a href="/" className={small?"logo small":"logo"}><span className="logo-core">N</span><span>Nexus</span></a>}
function Rail({page,query,type}){return <aside className="rail"><Logo/><div className="rail-label">EXPLORE</div>{SECTIONS.map(([k,l,I])=><a key={k} className={page==="search"&&type===k?"rail-item active":"rail-item"} href={query?"/search?q="+encodeURIComponent(query)+"&type="+k:"/"}><I size={17}/><span>{l}</span></a>)}<div className="rail-label">WORKSPACE</div><a className={page==="advanced"?"rail-item active":"rail-item"} href="/advanced"><SlidersHorizontal size={17}/><span>Advanced</span></a><a className={page==="settings"?"rail-item active":"rail-item"} href="/settings"><Settings size={17}/><span>Settings</span></a><div className="rail-bottom"><div className="nexus-status"><span></span><div><b>Nexus online</b><small>Search core ready</small></div></div></div></aside>}
function MobileHeader({input,setInput,submit,page}){return <header className="mobile-head"><Logo small/>{page==="search"&&<SearchBox value={input} onChange={setInput} onSubmit={submit}/>}<button className="menu"><Menu size={19}/></button></header>}
function Tabs({query,type}){return <div className="section-bar"><div className="section-scroll">{SECTIONS.map(([k,l,I])=><a key={k} className={type===k?"section-tab active":"section-tab"} href={"/search?q="+encodeURIComponent(query)+"&type="+k}><I size={15}/>{l}</a>)}<span className="query-chip">{query}</span></div></div>}
function Result({item,settings,index}){const u=item?.url||"",d=item?.domain||domain(u),target=settings.newTab?"_blank":"_self";return <article className="n-result" style={{"--delay":Math.min(index,8)*35+"ms"}}><div className="result-top"><span className="site-icon">{fav(u)?<img src={fav(u)} alt=""/>:<Globe2 size={12}/>}</span><span>{d||"web"}</span><span className="dot">•</span><span>source</span><button className="bookmark"><Bookmark size={14}/></button></div><a className="n-title" href={u||"#"} target={target} rel={target==="_blank"?"noopener noreferrer":undefined}>{item?.title||"Untitled result"}<ArrowUpRight size={15}/></a><p>{item?.description||"No description available."}</p>{u&&<div className="result-foot"><span>{u}</span><span className="open-dot">↗</span></div>}</article>}
function SpecialResults({type,results}){if(type==="images")return <div className="visual-grid">{results.map((x,i)=><a className="visual" key={x.url||i} href={x.url||"#"} target="_blank" rel="noopener noreferrer"><div>{x.thumbnail?<img src={x.thumbnail} alt="" loading="lazy"/>:<ImageIcon/>}</div><span>{x.title||"Image"}</span><small>{x.domain||domain(x.url)}</small></a>)}</div>;if(type==="news")return <div className="pulse">{results.map((x,i)=><a className="pulse-card" key={x.url||i} href={x.url} target="_blank" rel="noopener noreferrer">{x.thumbnail&&<img src={x.thumbnail} alt="" loading="lazy"/>}<div><small>{x.domain||domain(x.url)}{x.age?" · "+x.age:""}</small><strong>{x.title}</strong><p>{x.description||""}</p></div></a>)}</div>;return <div className="watch">{results.map((x,i)=><a className="watch-card" key={x.url||i} href={x.url} target="_blank" rel="noopener noreferrer"><div className="watch-thumb">{x.thumbnail?<img src={x.thumbnail} alt=""/>:<Play/>}<b><Play size={13} fill="currentColor"/></b></div><div><strong>{x.title}</strong><small>{x.domain||domain(x.url)}</small></div></a>)}</div>}
function Home({input,setInput,search,recent,saved}){return <main className="home"><div className="orb"><div className="orb-ring one"></div><div className="orb-ring two"></div><span>N</span></div><div className="home-kicker"><span></span>NEXUS SEARCH CORE</div><h1>Find what matters.</h1><p className="home-copy">One search surface for the web, ideas, stories, images and everything between.</p><SearchBox hero value={input} onChange={setInput} onSubmit={()=>search(input)}/><div className="home-actions"><button onClick={()=>search(input)}><Zap size={15}/> Explore</button><a href="/advanced"><SlidersHorizontal size={15}/> Tune search</a></div><div className="home-suggestions">{["quantum computing","molecular biology","space discoveries","learn TypeScript"].map(x=><button key={x} onClick={()=>search(x)}>{x}<ArrowUpRight size={13}/></button>)}</div>{(recent.length||saved.length)>0&&<div className="home-memory">{recent.length>0&&<div><label><Clock3 size={13}/>RECENT</label>{recent.slice(0,4).map(x=><button key={x} onClick={()=>search(x)}>{x}</button>)}</div>}{saved.length>0&&<div><label><Bookmark size={13}/>SAVED</label>{saved.slice(0,4).map(x=><button key={x} onClick={()=>search(x)}>{x}</button>)}</div>}</div>}</main>}
function SearchPage({query,type,search,results,loading,error,settings,saved,toggleSaved}){return <main className="search-main"><Tabs query={query} type={type}/><div className="results-wrap"><div className="results-head"><div><span className="eyebrow">{type==="all"?"DISCOVER":type.toUpperCase()}</span><h1>{query}</h1></div><button className={saved?"save active":"save"} onClick={()=>toggleSaved(query)}><Bookmark size={15} fill={saved?"currentColor":"none"}/>{saved?"Saved":"Save"}</button></div><div className="results-meta"><span>{loading?"NEXUS IS SEARCHING…":error?"SEARCH INTERRUPTED":results.length+" SOURCES"}</span><span className="live"><i></i>LIVE INDEX</span></div>{loading&&<div className="loading">{[1,2,3,4].map(i=><div key={i}><span/><span/><span/></div>)}</div>}{error&&!loading&&<div className="notice"><Sparkles/><div><b>Couldn’t reach the search layer.</b><p>{error}</p><button onClick={()=>search(query,type)}>Retry</button></div></div>}{!loading&&!error&&!results.length&&<div className="notice"><Compass/><div><b>Nothing surfaced.</b><p>Try another phrase, or explore a different section.</p></div></div>}{!loading&&!error&&type==="all"&&results.map((x,i)=><Result key={x.url||i} item={x} index={i} settings={settings}/>)}{!loading&&!error&&type!=="all"&&<SpecialResults type={type} results={results}/>}</div></main>}
function Utility({kind}){const data={about:["About Nexus","A custom search interface built around clarity, speed and exploration."],settings:["Settings","Shape the way Nexus behaves on this device."],advanced:["Advanced Search","Turn a natural idea into a precise search."]}[kind];return <main className="utility-page"><div className="utility-title"><span>{kind==="about"?"N":kind==="settings"?<Settings/>:<SlidersHorizontal/>}</span><div><small>NEXUS / {kind.toUpperCase()}</small><h1>{data[0]}</h1><p>{data[1]}</p></div></div>{kind==="about"?<div className="about-custom"><div><Sparkles/><b>Built differently.</b><p>Nexus is intentionally not a copy of another search engine. Its interface is designed around a compact command surface and a visual language of its own.</p></div><div><Globe2/><b>Open by default.</b><p>Results keep their source visible and put the actual destination one click away.</p></div></div>:kind==="settings"?<div className="settings-custom"><div><b>Search behavior</b><p>Preferences are stored locally on this device.</p></div><div><span>Safe Search</span><select defaultValue="Moderate"><option>Moderate</option><option>Strict</option><option>Off</option></select></div><div><span>Result density</span><select defaultValue="Comfortable"><option>Comfortable</option><option>Compact</option></select></div></div>:<div className="advanced-custom"><input placeholder="What are you trying to find?"/><div className="adv-row"><input placeholder="Exact phrase"/><input placeholder="Exclude words"/></div><input placeholder="Only search this domain"/><button>Build search <ArrowUpRight size={16}/></button></div>}</main>}
function App(){const[page,setPage]=useState(pageOf()),[query,setQuery]=useState(queryOf()),[type,setType]=useState(typeOf()),[input,setInput]=useState(queryOf()),[results,setResults]=useState([]),[loading,setLoading]=useState(!!queryOf()),[error,setError]=useState(""),[recent,setRecent]=useState(()=>read(RECENT,[])),[saved,setSaved]=useState(()=>read(SAVED,[])),[settings]=useState(()=>({...{safeSearch:"moderate",newTab:true},...read("nexus-settings",{})})),id=useRef(0);
const navigate=useCallback(u=>{history.pushState({}, "",u);setPage(pageOf());setQuery(queryOf());setType(typeOf());setInput(queryOf())},[]);
const addRecent=useCallback(q=>setRecent(a=>{const n=[q,...a.filter(x=>x.toLowerCase()!==q.toLowerCase())].slice(0,8);write(RECENT,n);return n}),[]);
const search=useCallback(async(v,t="all",opt={})=>{const q=String(v||"").trim();if(!q)return;const n=++id.current;if(!opt.noNav)navigate("/search?q="+encodeURIComponent(q)+"&type="+t);setQuery(q);setType(t);setInput(q);setLoading(true);setError("");try{const r=await fetch("/api/search?q="+encodeURIComponent(q)+"&type="+t+"&safe="+settings.safeSearch);const d=await r.json();if(!r.ok)throw Error(d.error||"Search failed");if(n!==id.current)return;setResults(Array.isArray(d.results)?d.results:[]);addRecent(q)}catch(e){if(n===id.current){setResults([]);setError(e.message||"Search failed")}}finally{if(n===id.current)setLoading(false)}},[navigate,settings.safeSearch,addRecent]);
useEffect(()=>{const pop=()=>{id.current++;setPage(pageOf());setQuery(queryOf());setType(typeOf());setInput(queryOf());if(pageOf()==="search"&&queryOf())search(queryOf(),typeOf(),{noNav:true});else{setResults([]);setLoading(false)}};addEventListener("popstate",pop);if(queryOf())search(queryOf(),typeOf(),{noNav:true});return()=>removeEventListener("popstate",pop)},[]);
const home=()=>{id.current++;navigate("/");setResults([]);setLoading(false);setError("")},toggle=q=>setSaved(a=>{const n=a.includes(q)?a.filter(x=>x!==q):[q,...a].slice(0,20);write(SAVED,n);return n});
return <div className="app"><Rail page={page} query={query} type={type}/><MobileHeader input={input} setInput={setInput} submit={()=>search(input)} page={page}/><div className="canvas">{page==="search"&&!query&&<Home input={input} setInput={setInput} search={search} recent={recent} saved={saved}/>} {page==="search"&&query&&<SearchPage query={query} type={type} search={search} results={results} loading={loading} error={error} settings={settings} saved={saved.includes(query)} toggleSaved={toggle}/>} {page!=="search"&&<Utility kind={page}/>}<footer><span>NEXUS</span><span>© 2026</span><a href="/about">About</a><a href="/settings">Settings</a><a href="https://github.com/Judson-web/NexAi-Neo" target="_blank">Source</a></footer></div></div>}
createRoot(document.getElementById("root")).render(<App/>);