import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{Copy,Download,ExternalLink,Gift,Image as ImageIcon,Link2,Menu,Search,ShieldCheck,Sparkles,X,CheckCircle,LoaderCircle,Github,BarChart3,Megaphone,Pencil,Trash2,MousePointerClick,LogOut,Plus,Eye,RefreshCw,AlertTriangle,Info,OctagonAlert}from"lucide-react";
import"./styles.css";
import AdminApp from"./AdminApp.jsx";
import LegalApp from"./LegalApp.jsx";
import InfoApp from"./InfoApp.jsx";


const imageUrl=(user,size=1024,format=user.format)=>"/api/discord-avatar?id="+encodeURIComponent(user.id)+"&hash="+encodeURIComponent(user.avatar)+"&format="+encodeURIComponent(format)+"&size="+encodeURIComponent(size);
const KINGSHOT_ICON="https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/ee/d2/22/eed22297-9313-d8b0-52c8-95f42a2795b2/AppIcon-0-0-1x_U007emarketing-0-8-0-85-220.png/0x0ss-85.png";
function KsLogo(){return <a className="brand ks-brand" href="/"><span className="brand-mark ks-brand-mark"><img src={KINGSHOT_ICON} alt="Kingshot"/></span><span>Kingshot Redeemer</span></a>}
function DiscordChip(){const [user,setUser]=useState(null);useEffect(()=>{let live=true;const load=()=>fetch("/api/discord-user?id=871756466900598815",{credentials:"same-origin",cache:"no-store",headers:{"cache-control":"no-cache"}}).then(r=>r.ok?r.json():null).then(d=>{if(live&&d?.id)setUser(d)}).catch(()=>{});load();const timer=setInterval(load,60000);return()=>{live=false;clearInterval(timer)}},[]);const avatar=user?.avatar?(user.avatarUrl||imageUrl(user,64,user.animated?"gif":"png")):"https://cdn.discordapp.com/embed/avatars/0.png?size=64";return <a className="admin-credit site-discord-credit" href="https://discord.com/channels/@me/871756466900598815" target="_blank" rel="noreferrer" aria-label="Message Judson on Discord"><img key={user?.avatar||"default"} src={avatar} alt="Judson" loading="eager" onError={e=>{e.currentTarget.src="https://cdn.discordapp.com/embed/avatars/0.png?size=64"}}/><span>Judson</span></a>}

function BannerAd({site="all",placement="top"}){const [ad,setAd]=useState(null);const [hidden,setHidden]=useState(false);
 useEffect(()=>{let live=true;setAd(null);setHidden(false);fetch("/api/banner-ads?site="+encodeURIComponent(site)+"&placement="+encodeURIComponent(placement),{credentials:"same-origin",cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>{if(live)setAd(d?.ad||null)}).catch(()=>{if(live)setAd(null)});return()=>{live=false}},[site,placement]);
 if(!ad||hidden)return null;
 const advertiser=ad.advertiser||"Sponsored";const headline=ad.headline||ad.alt_text||"Featured promotion";const cta=ad.cta_label||"Learn more";
 return <aside className={"banner-ad banner-ad-"+placement} aria-label="Advertisement">
  <div className="banner-ad-label"><span className="banner-ad-label-dot"/><Megaphone size={10}/><span>ADVERTISEMENT</span><span className="banner-ad-sponsored">Sponsored</span></div>
  <a className="banner-ad-card" href={"/api/banner-ad-click?id="+encodeURIComponent(ad.id)} target="_blank" rel="sponsored noopener" style={{"--ad-bg":ad.background||"#11131a"}}>
   <div className={"banner-ad-creative "+(!ad.image_url?"banner-ad-no-image":"")}>{ad.image_url?<img src={ad.image_url} alt={ad.alt_text||"Advertisement"}/>:<div className="banner-ad-copy"><span>{advertiser}</span><b>{headline}</b></div>}</div>
   <div className="banner-ad-body"><div className="banner-ad-meta"><span>{advertiser}</span><span className="banner-ad-dot">•</span><span>Sponsored</span></div><b className="banner-ad-headline">{headline}</b><span className="banner-ad-cta">{cta}<ExternalLink size={11}/></span></div>
   <button type="button" className="banner-ad-close" onClick={e=>{e.preventDefault();e.stopPropagation();setHidden(true)}} aria-label="Hide advertisement">×</button>
  </a>
 </aside>}
 
function KingshotApp(){
 const [playerId,setPlayerId]=useState(""),[code,setCode]=useState(""),[player,setPlayer]=useState(null),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(""),[menu,setMenu]=useState(false);
const redeem=async e=>{e.preventDefault();const id=playerId.trim(),gift=code.trim();if(!/^\d{5,20}$/.test(id)){setError("Enter a valid Kingshot Player ID.");return}if(!gift||gift.length>64){setError("Enter a valid gift code.");return}setBusy(true);setError("");setResult(null);try{let p=player;if(!p||String(p.governor_id||p.fid||p.id)!==id){const pr=await fetch("/api/kingshot-player?id="+encodeURIComponent(id));const pd=await pr.json();if(!pr.ok)throw Error(pd.error||"Could not find this player.");p=pd.player||pd;setPlayer(p)}const r=await fetch("/api/kingshot-redeem",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerId:id,code:gift,kid:String(p.kid??"")})});const d=await r.json();if(!r.ok)throw Error(d.error||"Redemption failed.");setResult(d)}catch(e){setError(e.message||"Redemption failed.")}finally{setBusy(false)}};
 return <div className="app ks-app"><a className="skip-link" href="#main-content">Skip to main content</a><header><KsLogo/><nav><a href="/auto">Auto Redeem</a><a href="/info">How it works</a></nav><div className="header-right"><DiscordChip/><button className="menu-btn" onClick={()=>setMenu(v=>!v)} aria-label="Menu"><Menu size={18}/></button></div></header>
 {menu&&<div className="mobile-menu"><a href="/auto" onClick={()=>setMenu(false)}>Auto Redeem</a><a href="/info" onClick={()=>setMenu(false)}>How it works</a></div>}<main><BannerAd site="kingshot" placement="top"/><section className="ks-hero" id="redeem"><div className="eyebrow"><span/>KINGSHOT GIFT CODE REDEEMER</div><h1>Claim your rewards.<br/><em>Manually.</em></h1><p className="hero-copy">Enter your Kingshot Player ID and gift code. We’ll look up your kingdom, then submit the redemption securely from the server.</p>
 <form className="ks-form manual-redeem-form" onSubmit={redeem}><div className="manual-form-head"><div><span className="manual-form-kicker">REDEMPTION DETAILS</span><h2>Enter your details</h2></div><span className="manual-secure"><ShieldCheck size={14}/> Server-side</span></div><div className="manual-fields"><div className="ks-field"><label htmlFor="manual-player-id">PLAYER ID</label><div><Search size={16}/><input id="manual-player-id" inputMode="numeric" autoComplete="off" value={playerId} onChange={e=>{setPlayerId(e.target.value.replace(/\D/g,""));setPlayer(null);setResult(null)}} placeholder="e.g. 43180889"/></div><small>Your Kingshot Player ID, not your kingdom number.</small></div><div className="ks-field"><label htmlFor="manual-gift-code">GIFT CODE</label><div><Gift size={16}/><input id="manual-gift-code" value={code} onChange={e=>setCode(e.target.value.replace(/\s/g,""))} placeholder="e.g. VIP777" autoCapitalize="characters" autoComplete="off" spellCheck="false"/></div><small>Codes are checked against the live redemption service.</small></div></div><button className="ks-submit manual-submit" disabled={busy}>{busy?<><LoaderCircle size={16} className="spin"/> Processing…</>:<><Gift size={16}/> Redeem Gift Code</>}</button></form>
 {error&&<div className="ks-error"><b>Couldn’t redeem that code.</b><span>{error}</span></div>}
 {player&&<div className="ks-player"><div className="ks-avatar">{player.avatar_url?<img src={player.avatar_url} alt=""/>:<span>{(player.nick_name||"K").slice(0,1)}</span>}</div><div><b>{player.nick_name||"Kingshot Player"}</b><span>Kingdom {player.kid ?? "—"} · TC {player.town_center_level ?? "—"}</span></div><CheckCircle size={17}/></div>}
 {result&&<div className={"ks-result "+(result.status==="SUCCESS"||result.status==="RECEIVED"||result.status==="SAME TYPE EXCHANGE"?"success":"") }><CheckCircle size={22}/><div><b>{result.statusLabel||result.status}</b><span>{result.message||"Redemption request completed."}</span></div></div>}
 </section><BannerAd site="kingshot" placement="middle"/><section className="ks-how" id="how"><div className="section-title"><span>01</span><h2>Simple by design.</h2></div><div className="feature-grid"><article><Search/><b>1. Find your player</b><p>Your Player ID is used to retrieve the current kingdom before redemption.</p></article><article><Gift/><b>2. Submit the code</b><p>The redemption request is signed server-side. Your signing secret is never exposed.</p></article><article><CheckCircle/><b>3. Get the result</b><p>We translate the game API response into a clear redemption status.</p></article></div></section><BannerAd site="kingshot" placement="bottom"/></main><footer><KsLogo/><span>Independent Kingshot community service. Not affiliated with Century Games.</span><span><a href="/info">How it works</a> · <a href="/terms?service=kingshot-manual">Terms</a> · <a href="/privacy?service=kingshot-manual">Privacy</a></span></footer></div>
}

function AutoRedeemApp(){
 const [ids,setIds]=useState(""),[busy,setBusy]=useState(false),[registered,setRegistered]=useState([]),[failed,setFailed]=useState([]),[error,setError]=useState(""),[menu,setMenu]=useState(false),[supportId,setSupportId]=useState(""),[supportReason,setSupportReason]=useState(""),[supportBusy,setSupportBusy]=useState(false),[supportSent,setSupportSent]=useState(false),[slideIndex,setSlideIndex]=useState(0),[swipeHint,setSwipeHint]=useState(true);
 const register=async e=>{e.preventDefault();const raw=[...new Set(ids.split(/[\s,;]+/).map(v=>v.trim()).filter(Boolean))];if(!raw.length){setError("Enter at least one Kingshot Player ID.");return}setBusy(true);setError("");setRegistered([]);setFailed([]);try{const results=[],failures=[];for(const id of raw){if(!/^[0-9]{5,20}$/.test(id)){failures.push({id,error:"Invalid Player ID format."});setFailed([...failures]);continue}try{const pr=await fetch("/api/kingshot-player?id="+encodeURIComponent(id));const pd=await pr.json().catch(()=>({}));if(!pr.ok)throw Error(pd.error||"Player not found");const p=pd.player||pd;const r=await fetch("/api/kingshot-register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerId:id,kingdomId:String(p.kid??""),playerName:p.nick_name||p.name||p.nickname||"Kingshot Player",avatarUrl:p.avatar_url||p.avatar||p.avatarUrl||""})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not register player");results.push({id,name:p.nick_name||p.name||"Kingshot Player",kingdom:p.kid??"—",avatar:p.avatar_url||p.avatar||p.avatarUrl||"",alreadyRegistered:Boolean(d.alreadyRegistered),registrationStatus:d.registrationStatus||((d.alreadyRegistered)?"ALREADY_REGISTERED":"NEW")});setRegistered([...results])}catch(err){failures.push({id,error:err.message||"Registration failed."});setFailed([...failures])}}if(!results.length&&failures.length)setError("No players were registered. Check the results below.");}catch(e){setError(e.message||"Registration failed.")}finally{setBusy(false)}};
 const existing=registered.filter(p=>p.registrationStatus==="ALREADY_REGISTERED"),reactivated=registered.filter(p=>p.registrationStatus==="REACTIVATED"),newPlayers=registered.filter(p=>p.registrationStatus==="NEW");
 const PlayerRow=({p})=><div className="ks-registered-row"><div className="ks-avatar">{p.avatar?<img src={p.avatar} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display="none"}}/>:<Gift size={16}/>}</div><div><b>{p.name}</b><span>Player ID {p.id} · Kingdom {p.kingdom}</span></div></div>;
 const ProfileSlides=({players})=><><div className="ks-profile-slides" onScroll={e=>{const el=e.currentTarget,i=Math.round(el.scrollLeft/el.clientWidth);if(i!==slideIndex)setSlideIndex(i);if(swipeHint)setSwipeHint(false)}} onTouchStart={()=>setSwipeHint(false)}>{players.map(p=><PlayerRow key={p.id} p={p}/>)}</div><div className="ks-profile-slide-meta" aria-live="polite"><span>{Math.min(slideIndex+1,players.length)} / {players.length}</span>{swipeHint&&<small>Swipe for more</small>}<div className="ks-profile-dots">{players.map((p,i)=><i key={p.id} className={i===slideIndex?"active":""}/>)}</div></div></>;
 return <div className="app ks-app"><header><KsLogo/><nav><a href="/manual">Manual Redeem</a><a href="/info">How it works</a></nav><div className="header-right"><DiscordChip/><button className="menu-btn" onClick={()=>setMenu(v=>!v)} aria-label="Menu"><Menu size={18}/></button></div></header>{menu&&<div className="mobile-menu"><a href="/manual" onClick={()=>setMenu(false)}>Manual Redeem</a><a href="/info" onClick={()=>setMenu(false)}>How it works</a></div>}<main><BannerAd site="kingshot" placement="top"/><section className="ks-auto-hero"><div className="eyebrow"><span/>KINGSHOT AUTO REDEEM</div><h1>Never miss a gift code.<br/><em>Let it run for you.</em></h1><p className="hero-copy">Register your Kingshot Player ID once. Active gift codes are checked automatically, including older codes that are still valid.</p><form className="ks-register-box" onSubmit={register}><div className="ks-register-field"><label>PLAYER ID(S)</label><div><Gift size={17}/><input inputMode="text" enterKeyHint="done" value={ids} onChange={e=>setIds(e.target.value)} placeholder="Enter one or more Player IDs" autoComplete="off" spellCheck="false"/></div><small>Separate multiple IDs with spaces, commas, or semicolons.</small></div><button className="ks-submit" disabled={busy}>{busy?<><span className="register-spinner" aria-hidden="true"><LoaderCircle size={16}/></span><span>Checking players…</span></>:"Register for Auto Redeem"}</button></form>{error&&<div className="ks-error"><b>Registration needs attention.</b><span>{error}</span></div>}
 {newPlayers.length>0&&<div className="ks-registered ks-registered-new"><div className="ks-registered-head"><div><span className="result-label">REGISTRATION COMPLETE</span><h2>{newPlayers.length} player{newPlayers.length===1?"":"s"} registered</h2></div><CheckCircle size={22}/></div>{newPlayers.length>1?<ProfileSlides players={newPlayers}/>:newPlayers.map(p=><PlayerRow key={p.id} p={p}/>)}</div>}
 {existing.length>0&&<div className="ks-registered ks-registered-existing"><div className="ks-registered-head"><div><span className="result-label">ALREADY ACTIVE</span><h2>{existing.length} player{existing.length===1?"":"s"} already active</h2></div><ShieldCheck size={22}/></div><div className="ks-existing-note">These Player IDs are already enrolled. No changes were needed.</div>{existing.map(p=><PlayerRow key={p.id} p={p}/>)}</div>}
 {reactivated.length>0&&<div className="ks-registered ks-registered-new"><div className="ks-registered-head"><div><span className="result-label">WELCOME BACK</span><h2>{reactivated.length} player{reactivated.length===1?"":"s"} re-enabled</h2></div><CheckCircle size={22}/></div><div className="ks-existing-note">These previous registrations were re-enabled for auto-redeem.</div>{reactivated.length>1?<ProfileSlides players={reactivated}/>:reactivated.map(p=><PlayerRow key={p.id} p={p}/>)}</div>}{failed.length>0&&<div className="ks-registered ks-registered-existing"><div className="ks-registered-head"><div><span className="result-label">NOT REGISTERED</span><h2>{failed.length} player{failed.length===1?"":"s"} need attention</h2></div><X size={22}/></div><div className="ks-existing-note">Each failed ID was skipped independently, so valid IDs in the same submission can still be processed.</div>{failed.map(f=><div className="ks-registered-row" key={"failed-"+f.id}><div className="ks-avatar"><X size={16}/></div><div><b>Player ID {f.id}</b><span>{f.error}</span></div></div>)}</div>}
 </section><BannerAd site="kingshot" placement="middle"/><section className="ks-support"><div className="section-title"><span>SUPPORT</span><h2>Need a registration removed?</h2></div><p className="ks-support-copy">Send us the Player ID and a short reason. An admin will review the request and either revoke the auto-redeem registration or close the ticket.</p><form className="ks-support-form" onSubmit={async e=>{e.preventDefault();const id=supportId.trim(),reason=supportReason.trim();if(!/^[0-9]{5,20}$/.test(id)){setError("Enter a valid Player ID for the support request.");return}if(reason.length<5){setError("Please explain the removal request in a little more detail.");return}setSupportBusy(true);setSupportSent(false);setError("");try{const r=await fetch("/api/kingshot-support",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerId:id,reason})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not submit support request.");setSupportId("");setSupportReason("");setSupportSent(true)}catch(e){setError(e.message||"Could not submit support request.")}finally{setSupportBusy(false)}}}><div className="ks-register-field"><label>PLAYER ID TO REMOVE</label><div><Gift size={17}/><input inputMode="numeric" value={supportId} onChange={e=>setSupportId(e.target.value.replace(/\D/g,""))} placeholder="e.g. 43180889"/></div></div><label className="ks-support-reason"><span>REASON</span><textarea value={supportReason} onChange={e=>setSupportReason(e.target.value.slice(0,1000))} placeholder="Tell the admin why this registration should be removed." rows="4"/></label><button className="ks-submit" disabled={supportBusy}>{supportBusy?<><LoaderCircle size={16} className="spin"/> Sending…</>:"Send removal request"}</button></form>{supportSent&&<div className="ks-support-success"><CheckCircle size={17}/><span>Request sent. An admin will review it shortly.</span></div>}</section><section className="ks-auto-how" id="how"><div className="section-title"><span>01</span><h2>How automatic redemption works.</h2></div><div className="feature-grid"><article><Gift/><b>1. Register once</b><p>If the Player ID is already registered, we show it separately instead of treating it as a new registration.</p></article><article><Gift/><b>2. Recover missed codes</b><p>Every active code is checked against that player's redemption history, including older valid codes.</p></article><article><CheckCircle/><b>3. Redeem safely</b><p>Each player/code pair is claimed atomically, so overlapping workers cannot submit the same redemption twice.</p></article></div></section><BannerAd site="kingshot" placement="bottom"/></main><footer><KsLogo/><span>Automatic redemption is a community service. Not affiliated with Century Games.</span><span><a href="/info">How it works</a> · <a href="/terms?service=kingshot-auto">Terms</a> · <a href="/privacy?service=kingshot-auto">Privacy</a></span></footer></div>
}function validateAdForm(form){
 const text=/^[^<>\u0000-\u001F]{1,200}$/;
 const name=/^[A-Za-z0-9][A-Za-z0-9 ._&'’()\-]{0,99}$/;
 const url=/^https?:\/\/[^\s<>]+$/i;
 const color=/^#[0-9a-fA-F]{6}$/;
 if(!name.test(String(form.name||"").trim()))return "Campaign name: use 1–100 letters, numbers, spaces or . _ & ' - ( ).";
 if(form.advertiser&&!text.test(String(form.advertiser).trim()))return "Advertiser contains unsupported characters.";
 if(form.image_url&&!url.test(String(form.image_url).trim()))return "Banner image URL must be a valid http(s) URL.";
 if(!url.test(String(form.click_url||"").trim()))return "Destination URL must be a valid http(s) URL.";
 if(form.headline&&!/^.{1,180}$/s.test(String(form.headline)))return "Headline must be 1–180 characters.";
 if(!/^.{1,50}$/s.test(String(form.cta_label||"")))return "CTA label must be 1–50 characters.";
 if(!/^.{1,200}$/s.test(String(form.alt_text||"")))return "Alt text must be 1–200 characters.";
 if(!color.test(String(form.background||"")))return "Background must be a 6-digit hex color such as #11131a.";
 if(form.starts_at&&form.ends_at&&new Date(form.ends_at).getTime()<=new Date(form.starts_at).getTime())return "End time must be later than start time.";
 return "";
}

function BannerAdsAdminApp(){
 const empty={id:null,name:"",advertiser:"",site:"all",placement:"top",image_url:"",click_url:"https://",alt_text:"Advertisement",headline:"",cta_label:"Learn more",background:"#11131a",active:true,starts_at:"",ends_at:""};
 const [auth,setAuth]=useState(false),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[ads,setAds]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const load=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-data",{credentials:"same-origin",cache:"no-store",headers:{"cache-control":"no-cache"}});const d=await r.json().catch(()=>({}));if(r.status===401){setAuth(false);setAds([]);return}if(!r.ok)throw Error(d.error||"Could not load ad manager.");setAuth(true);setAds(d.bannerAds||[])}catch(e){setError(e.message||"Could not load ad manager.")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const login=async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/kingshot-admin-login",{method:"POST",headers:{"content-type":"application/json","cache-control":"no-cache"},credentials:"same-origin",cache:"no-store",body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Invalid credentials.");setPassword("");await load()}catch(e){setError(e.message||"Login failed.");setBusy(false)}};
 const logout=async()=>{await fetch("/api/kingshot-admin-login",{method:"DELETE",credentials:"same-origin"}).catch(()=>{});setAuth(false);setAds([])};
 const reset=()=>{setForm({...empty});setEditing(false);setError("")};
 const localDateTime=value=>{if(!value)return "";const d=new Date(value);if(Number.isNaN(d.getTime()))return "";const pad=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate())+"T"+pad(d.getHours())+":"+pad(d.getMinutes())};
 const editAd=a=>{setForm({...empty,...a,site:a.site||"all",placement:a.placement||"top",active:a.active!==false,starts_at:localDateTime(a.starts_at),ends_at:localDateTime(a.ends_at)});setEditing(true);setError("");window.scrollTo({top:0,behavior:"smooth"})};
 const save=async e=>{e.preventDefault();const validation=validateAdForm(form);if(validation){setError(validation);return}setSaving(true);setError("");try{const payload={adAction:"upsert",...form,id:form.id||null,site:form.site||"all",placement:form.placement||"top",starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,ends_at:form.ends_at?new Date(form.ends_at).toISOString():null};const r=await fetch("/api/kingshot-admin-data",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not save advertisement.");setAds(d.bannerAds||[]);reset()}catch(e){setError(e.message||"Could not save advertisement.")}finally{setSaving(false)}};
 const remove=async id=>{if(!confirm("Delete this advertisement permanently?"))return;setSaving(true);setError("");try{const r=await fetch("/api/kingshot-admin-data",{method:"DELETE",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({adAction:"delete",id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not delete advertisement.");setAds(d.bannerAds||[]);if(form.id===id)reset()}catch(e){setError(e.message||"Could not delete advertisement.")}finally{setSaving(false)}};
 const toggle=async a=>{const payload={adAction:"upsert",...a,active:!a.active,starts_at:a.starts_at,ends_at:a.ends_at};setSaving(true);try{const r=await fetch("/api/kingshot-admin-data",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Could not update advertisement.");setAds(d.bannerAds||[])}catch(e){setError(e.message||"Could not update advertisement.")}finally{setSaving(false)}};
 const totalImpressions=ads.reduce((n,a)=>n+Number(a.impressions||0),0),totalUniqueImpressions=ads.reduce((n,a)=>n+Number(a.unique_impressions||0),0),totalRawClicks=ads.reduce((n,a)=>n+Number((a.raw_clicks??a.clicks??0)),0),totalUniqueClicks=ads.reduce((n,a)=>n+Number((a.unique_clicks??a.clicks??0)),0),active=ads.filter(a=>a.active).length;
 const totalClicks=totalUniqueClicks,ctr=totalImpressions?((totalRawClicks/totalImpressions)*100).toFixed(2):"0.00",uniqueCtr=totalUniqueImpressions?((totalUniqueClicks/totalUniqueImpressions)*100).toFixed(2):"0.00";
 const metricsBaseline=ads.map(a=>a.metrics_baseline_at).filter(Boolean).sort()[0]||null;
 const campaignStatus=a=>{const now=Date.now(),start=a.starts_at?new Date(a.starts_at).getTime():null,end=a.ends_at?new Date(a.ends_at).getTime():null;if(!a.active)return["PAUSED","off"];if(start&&start>now)return["SCHEDULED","scheduled"];if(end&&end<=now)return["EXPIRED","expired"];return["LIVE","live"]};
 const adCtr=a=>Number(a.impressions)?((Number(a.clicks||0)/Number(a.impressions))*100).toFixed(2)+"%":"0.00%";
 if(busy)return <div className="app ad-admin-app"><main className="ad-admin-loading"><LoaderCircle className="spin" size={24}/><span>Checking admin session…</span></main></div>;
 if(!auth)return <div className="app ad-admin-app"><header><KsLogo/><div className="admin-badge"><ShieldCheck size={12}/> ADMIN ONLY</div></header><main className="ad-login-wrap"><section className="ad-login-card"><div className="eyebrow"><span/>SECURE AD MANAGEMENT</div><h1>Advertisement<br/><em>control room.</em></h1><p>Sign in with the existing Kingshot admin account to create, schedule and manage banner ads across the public sites.</p><form onSubmit={login}><label>ADMIN EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>ADMIN PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="ks-submit" disabled={busy}>Sign in to Ad Manager</button></form>{error&&<div className="ks-error"><b>Authentication failed.</b><span>{error}</span></div>}</section></main></div>;
 return <div className="app ad-admin-app"><header><KsLogo/><nav><a href="/ks-admin">Admin</a><a href="/ad-admin">Ads</a></nav><div className="header-right"><div className="admin-badge"><ShieldCheck size={12}/> ADMIN</div><button className="menu-btn" onClick={logout} aria-label="Sign out"><LogOut size={16}/></button></div></header>
 <main className="ad-admin-main"><section className="ad-admin-head"><div><div className="eyebrow"><span/>BANNER AD MANAGER</div><h1>Put your ads<br/><em>where people see them.</em></h1><p>Build restrained, clearly labeled campaigns with targeting, scheduling, live previews and deduplicated performance counts.</p></div><div className="ad-head-actions"><button className="ad-ghost" onClick={load} disabled={busy}><RefreshCw size={14}/> Refresh</button><button className="ad-primary" onClick={reset}><Plus size={15}/> New banner</button></div></section>
 <section className="ad-stats"><div><small>CAMPAIGNS</small><b>{ads.length}</b></div><div><small>ACTIVE</small><b>{active}</b></div><div><small>IMPRESSIONS</small><b>{totalImpressions.toLocaleString()}</b></div><div><small>CLICKS</small><b>{totalClicks.toLocaleString()}</b></div><div><small>CTR</small><b>{ctr}%</b></div></section>{metricsBaseline&&<p className="ad-metrics-note">Metrics baseline: {new Date(metricsBaseline).toLocaleDateString()} · clicks are deduplicated per visitor within the measurement window.</p>}
 {error&&<div className="admin-inline-error">{error}</div>}
 <div className="ad-admin-grid"><section className="ad-editor"><div className="ad-editor-head"><div><span className="result-label">{editing?"EDIT BANNER":"CREATE BANNER"}</span><h2>{editing?"Update campaign":"New advertisement"}</h2></div>{editing&&<button className="ad-ghost" onClick={reset}>Cancel</button>}</div>
 <form onSubmit={save} className="ad-form">
 <div className="ad-form-section"><div className="ad-form-section-head"><span>01</span><div><b>Campaign</b><small>Give the campaign a name and choose its audience.</small></div></div>
  <div className="ad-form-two"><label>CAMPAIGN NAME<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="September Partner" maxLength="100" required/></label><label>ADVERTISER<input value={form.advertiser} onChange={e=>setForm({...form,advertiser:e.target.value})} placeholder="Brand / sponsor"/></label></div>
  <div className="ad-form-two"><label>WEBSITE<select value={form.site} onChange={e=>setForm({...form,site:e.target.value})}><option value="all">All websites</option><option value="kingshot">Kingshot</option><option value="discord">Discord PFP</option></select></label><label>PLACEMENT<select value={form.placement} onChange={e=>setForm({...form,placement:e.target.value})}><option value="top">Top</option><option value="middle">Middle</option><option value="bottom">Bottom</option></select></label></div>
 </div>
 <div className="ad-form-section"><div className="ad-form-section-head"><span>02</span><div><b>Creative</b><small>Use an image, headline and call to action.</small></div></div>
  <label>BANNER IMAGE URL<input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value.trimStart()})} placeholder="https://cdn.example.com/banner.jpg" inputMode="url" pattern="https?://[^\\s<>]+" title="Use a valid http(s) image URL."/></label>
  <div className="ad-form-two"><label>HEADLINE<input value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})} placeholder="Short promotional headline" maxLength="180"/></label><label>CTA LABEL<input value={form.cta_label} onChange={e=>setForm({...form,cta_label:e.target.value})} placeholder="Learn more" maxLength="50"/></label></div>
 </div>
 <div className="ad-form-section"><div className="ad-form-section-head"><span>03</span><div><b>Delivery</b><small>Set the destination and campaign timing.</small></div></div>
  <label>DESTINATION URL<input value={form.click_url} onChange={e=>setForm({...form,click_url:e.target.value.trimStart()})} placeholder="https://example.com" inputMode="url" pattern="https?://[^\\s<>]+" title="Use a valid http(s) destination URL." required/></label>
  <div className="ad-form-two"><label>STARTS AT<input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>ENDS AT<input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label></div>
  <label className="ad-toggle"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span><b>Campaign enabled</b><small>Only enabled campaigns within their schedule can serve.</small></span></label>
 </div>
 <details className="ad-advanced"><summary>Advanced options</summary><div className="ad-advanced-grid"><label>ALT TEXT<input value={form.alt_text} onChange={e=>setForm({...form,alt_text:e.target.value})} placeholder="Advertisement" maxLength="200"/></label><label>BACKGROUND<input value={form.background} onChange={e=>setForm({...form,background:e.target.value})} placeholder="#11131a"/></label></div><small>Alt text improves accessibility. Background is used when the creative has no image.</small></details>
 <div className="ad-form-actions"><button type="button" className="ad-ghost" onClick={reset}>Reset</button><button className="ad-primary ad-save" disabled={saving}>{saving?<><LoaderCircle size={15} className="spin"/> Saving…</>:<><Megaphone size={15}/> {editing?"Update campaign":"Publish campaign"}</>}</button></div>
 </form></section>
 <section className="ad-preview-panel"><div className="ad-editor-head"><div><span className="result-label">LIVE PREVIEW</span><h2>What visitors see</h2></div></div><div className="ad-preview-shell"><div className="banner-ad-label"><Megaphone size={10}/>ADVERTISEMENT</div><div className="banner-ad-card" style={{"--ad-bg":form.background||"#11131a"}}>{form.image_url?<div className="banner-ad-creative"><img src={form.image_url} alt={form.alt_text||"Advertisement"}/></div>:<div className="banner-ad-creative"><div className="banner-ad-copy"><span>{form.advertiser||"Sponsored"}</span><b>{form.headline||"Your promotional headline"}</b><small>{form.cta_label||"Learn more"}</small></div></div>}</div></div><p className="ad-preview-note">Banners are responsive and labeled as advertisements. Clicks are routed through the server so the manager can count them.</p></section></div>
 <section className="ad-list-section"><div className="ad-editor-head"><div><span className="result-label">CAMPAIGNS</span><h2>Published banners</h2></div><div className="ad-rotation-note"><MousePointerClick size={12}/><span>Multiple banners in the same website + placement rotate automatically. Visitors see one banner at a time.</span></div></div><div className="ad-list">{ads.length?ads.map(a=>{const [status,statusClass]=campaignStatus(a);return <article className={"ad-row "+statusClass} key={a.id}><div className="ad-row-thumb" style={{"--ad-bg":a.background||"#11131a"}}>{a.image_url?<img src={a.image_url} alt=""/>:<Megaphone size={19}/>}</div><div className="ad-row-main"><div><b>{a.name}</b><span>{a.advertiser||"No advertiser"} · {a.site} · {a.placement}</span><div className={"ad-status "+statusClass}>{status}</div></div><div className="ad-row-metrics"><span><Eye size={12}/>{Number(a.impressions||0).toLocaleString()} raw</span><span><Eye size={12}/>{Number(a.unique_impressions||0).toLocaleString()} unique</span><span><MousePointerClick size={12}/>{Number((a.raw_clicks??a.clicks??0)).toLocaleString()} raw</span><span><MousePointerClick size={12}/>{Number((a.unique_clicks??a.clicks??0)).toLocaleString()} unique</span><span>{Number(a.impressions)?((Number((a.raw_clicks??a.clicks??0))/Number(a.impressions))*100).toFixed(2):"0.00"}% raw CTR</span><span>{Number(a.unique_impressions)?((Number((a.unique_clicks??a.clicks??0))/Number(a.unique_impressions))*100).toFixed(2):"0.00"}% unique CTR</span></div></div><div className="ad-row-actions"><button className="ad-action-toggle" onClick={()=>toggle(a)} disabled={saving}>{a.active?"Disable":"Enable"}</button><button className="ad-action-edit" onClick={()=>editAd(a)}><Pencil size={13}/> Edit</button><button className="ad-action-delete" onClick={()=>remove(a.id)}><Trash2 size={13}/> Delete</button></div></article>;}):<div className="ad-empty"><Megaphone size={22}/><b>No banners yet</b><span>Create one above and it will appear on the selected website once active.</span></div>}</div></section>
 </main></div>;
}

function MaintenanceScreen(){const [state,setState]=useState(null),[now,setNow]=useState(Date.now());useEffect(()=>{let live=true;const load=()=>fetch("/api/kingshot-admin-data?public=maintenance",{credentials:"same-origin",cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>{if(live)setState(d||{maintenanceEnabled:false})}).catch(()=>{if(live)setState({maintenanceEnabled:false})});load();const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{live=false;clearInterval(timer)}},[]);useEffect(()=>{if(state?.maintenanceEnabled&&state?.endsAt){const remaining=new Date(state.endsAt).getTime()-now;if(remaining<=0)location.reload()}},[state,now]);if(!state||!state.maintenanceEnabled)return null;const remaining=state.endsAt?Math.max(0,new Date(state.endsAt).getTime()-now):null;const totalSeconds=remaining===null?null:Math.ceil(remaining/1000),days=totalSeconds===null?0:Math.floor(totalSeconds/86400),hours=totalSeconds===null?0:Math.floor((totalSeconds%86400)/3600),minutes=totalSeconds===null?0:Math.floor((totalSeconds%3600)/60),seconds=totalSeconds===null?0:totalSeconds%60;return <div className="app ks-app" style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:"24px"}}><main style={{width:"min(680px,100%)",textAlign:"center"}}><section className="admin-hero"><div className="eyebrow"><span/>TEMPORARILY UNAVAILABLE</div><h1>We’ll be <em>back shortly.</em></h1><p className="hero-copy" style={{whiteSpace:"pre-wrap"}}>{state.message||"We are performing maintenance right now. Please check back shortly."}</p>{remaining!==null&&<div style={{margin:"28px auto 0",display:"grid",gridTemplateColumns:days? "repeat(4,minmax(0,1fr))":"repeat(3,minmax(0,1fr))",gap:8,maxWidth:460}}>{days>0&&<div className="admin-stats"><div><small>DAYS</small><b>{days}</b></div></div>}<div className="admin-stats"><div><small>HOURS</small><b>{String(hours).padStart(2,"0")}</b></div></div><div className="admin-stats"><div><small>MINUTES</small><b>{String(minutes).padStart(2,"0")}</b></div></div><div className="admin-stats"><div><small>SECONDS</small><b>{String(seconds).padStart(2,"0")}</b></div></div></div>}</section></main></div>}
const announcementIcon=t=>t==="success"?CheckCircle:t==="warning"?AlertTriangle:t==="important"?OctagonAlert:Info;
function AnnouncementCard({item}){if(!item)return null;const C=announcementIcon(item.type||"info");return <aside className={"site-announcement site-announcement-"+(item.type||"info")}><div className="site-announcement-icon"><C size={17}/></div><div className="site-announcement-content"><b>{item.title||"Announcement title"}</b><p>{item.message||"Your announcement message will appear here."}</p>{item.link_url&&<a href={item.link_url} target="_blank" rel="noopener noreferrer">{item.link_label||"Learn more"} <ExternalLink size={11}/></a>}</div></aside>}
function PublicAnnouncements({children}){const[state,setState]=useState(null);useEffect(()=>{fetch("/api/kingshot-admin-data?public=announcements").then(r=>r.ok?r.json():null).then(d=>setState(d?.announcements||[])).catch(()=>setState([]))},[]);return <>{state?.[0]&&<div style={{maxWidth:"1180px",margin:"0 auto",padding:"14px 20px 0"}}><AnnouncementCard item={state[0]}/></div>}{children}</>}
function PublicMaintenance({children}){const [state,setState]=useState(null);useEffect(()=>{let live=true;fetch("/api/kingshot-admin-data?public=maintenance",{credentials:"same-origin",cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>{if(live)setState(d||{maintenanceEnabled:false})}).catch(()=>{if(live)setState({maintenanceEnabled:false})});return()=>{live=false}},[]);return state?.maintenanceEnabled?<MaintenanceScreen/>:children}
const publicPage=location.pathname==="/auto"||location.pathname==="/" ? <AutoRedeemApp/>:location.pathname==="/manual"||location.pathname==="/redeem" ? <KingshotApp/>:location.pathname==="/info"?<InfoApp/>:location.pathname==="/terms"?<LegalApp type="terms"/>:location.pathname==="/privacy"?<LegalApp type="privacy"/>:<AutoRedeemApp/>; createRoot(document.getElementById("root")).render(location.pathname==="/ks-admin"?<AdminApp/>:location.pathname==="/ad-admin"?<BannerAdsAdminApp/>:<PublicMaintenance><PublicAnnouncements>{publicPage}</PublicAnnouncements></PublicMaintenance>);